#pragma once

#include <map>

struct PaintNames_t
{
	const char* displayName = nullptr;
	const char* paintName = nullptr;
};

const std::map<int, PaintNames_t> itemSkins = {
		{ -1, { "No Skin" } },
		{2, {"Groundwater", "Groundwater"} },
		{3, {"Candy Apple", "Candy Apple"} },
		{5, {"Forest DDPAT", "Forest DDPAT"} },
		{6, {"Arctic Camo", "Arctic Camo"} },
		{8, {"Desert Storm", "Desert Storm"} },
		{9, {"Bengal Tiger", "Bengal Tiger"} },
		{10, {"Copperhead", "Copperhead"} },
		{11, {"Skulls", "Skulls"} },
		{12, {"Crimson Web", "Crimson Web"} },
		{13, {"Blue Streak", "Blue Streak"} },
		{14, {"Red Laminate", "Red Laminate"} },
		{15, {"Gunsmoke", "Gunsmoke"} },
		{16, {"Jungle Tiger", "Jungle Tiger"} },
		{17, {"Urban DDPAT", "Urban DDPAT"} },
		{20, {"Virus", "Virus"} },
		{21, {"Granite Marbleized", "Granite Marbleized"} },
		{22, {"Contrast Spray", "Contrast Spray"} },
		{25, {"Forest Leaves", "Forest Leaves"} },
		{26, {"Lichen Dashed", "Lichen Dashed"} },
		{27, {"Bone Mask", "Bone Mask"} },
		{28, {"Anodized Navy", "Anodized Navy"} },
		{30, {"Snake Camo", "Snake Camo"} },
		{32, {"Silver", "Silver"} },
		{33, {"Hot Rod", "Hot Rod"} },
		{34, {"Metallic DDPAT", "Metallic DDPAT"} },
		{36, {"Ossified", "Ossified"} },
		{37, {"Blaze", "Blaze"} },
		{38, {"Fade", "Fade"} },
		{39, {"Bulldozer", "Bulldozer"} },
		{40, {"Night", "Night"} },
		{41, {"Copper", "Copper"} },
		{42, {"Blue Steel", "Blue Steel"} },
		{43, {"Stained", "Stained"} },
		{44, {"Case Hardened", "Case Hardened"} },
		{46, {"Contractor", "Contractor"} },
		{47, {"Colony", "Colony"} },
		{48, {"Dragon Tattoo", "Dragon Tattoo"} },
		{51, {"Lightning Strike", "Lightning Strike"} },
		{59, {"Slaughter", "Slaughter"} },
		{60, {"Dark Water", "Dark Water"} },
		{61, {"Hypnotic", "Hypnotic"} },
		{62, {"Bloomstick", "Bloomstick"} },
		{67, {"Cold Blooded", "Cold Blooded"} },
		{70, {"Carbon Fiber", "Carbon Fiber"} },
		{71, {"Scorpion", "Scorpion"} },
		{72, {"Safari Mesh", "Safari Mesh"} },
		{73, {"Wings", "Wings"} },
		{74, {"Polar Camo", "Polar Camo"} },
		{75, {"Blizzard Marbleized", "Blizzard Marbleized"} },
		{76, {"Winter Forest", "Winter Forest"} },
		{77, {"Boreal Forest", "Boreal Forest"} },
		{78, {"Forest Night", "Forest Night"} },
		{83, {"Orange DDPAT", "Orange DDPAT"} },
		{84, {"Pink DDPAT", "Pink DDPAT"} },
		{90, {"Mudder", "Mudder"} },
		{92, {"Cyanospatter", "Cyanospatter"} },
		{93, {"Caramel", "Caramel"} },
		{95, {"Grassland", "Grassland"} },
		{96, {"Blue Spruce", "Blue Spruce"} },
		{98, {"Ultraviolet", "Ultraviolet"} },
		{99, {"Sand Dune", "Sand Dune"} },
		{100, {"Storm", "Storm"} },
		{101, {"Tornado", "Tornado"} },
		{102, {"Whiteout", "Whiteout"} },
		{104, {"Grassland Leaves", "Grassland Leaves"} },
		{107, {"Polar Mesh", "Polar Mesh"} },
		{110, {"Condemned", "Condemned"} },
		{111, {"Glacier Mesh", "Glacier Mesh"} },
		{116, {"Sand Mesh", "Sand Mesh"} },
		{119, {"Sage Spray", "Sage Spray"} },
		{122, {"Jungle Spray", "Jungle Spray"} },
		{124, {"Sand Spray", "Sand Spray"} },
		{125, {"X-Ray", "X-Ray"} },
		{135, {"Urban Perforated", "Urban Perforated"} },
		{136, {"Waves Perforated", "Waves Perforated"} },
		{141, {"Orange Peel", "Orange Peel"} },
		{143, {"Urban Masked", "Urban Masked"} },
		{147, {"Jungle Dashed", "Jungle Dashed"} },
		{148, {"Sand Dashed", "Sand Dashed"} },
		{149, {"Urban Dashed", "Urban Dashed"} },
		{151, {"Jungle", "Jungle"} },
		{153, {"Demolition", "Demolition"} },
		{154, {"Afterimage", "Afterimage"} },
		{155, {"Bullet Rain", "Bullet Rain"} },
		{156, {"Death by Kitty", "Death by Kitty"} },
		{157, {"Palm", "Palm"} },
		{158, {"Walnut", "Walnut"} },
		{159, {"Brass", "Brass"} },
		{162, {"Splash", "Splash"} },
		{164, {"Modern Hunter", "Modern Hunter"} },
		{165, {"Splash Jam", "Splash Jam"} },
		{166, {"Blaze Orange", "Blaze Orange"} },
		{167, {"Radiation Hazard", "Radiation Hazard"} },
		{168, {"Nuclear Threat", "Nuclear Threat"} },
		{169, {"Fallout Warning", "Fallout Warning"} },
		{170, {"Predator", "Predator"} },
		{171, {"Irradiated Alert", "Irradiated Alert"} },
		{172, {"Black Laminate", "Black Laminate"} },
		{174, {"BOOM", "BOOM"} },
		{175, {"Scorched", "Scorched"} },
		{176, {"Faded Zebra", "Faded Zebra"} },
		{177, {"Memento", "Memento"} },
		{178, {"Doomkitty", "Doomkitty"} },
		{179, {"Nuclear Threat", "Nuclear Threat"} },
		{180, {"Fire Serpent", "Fire Serpent"} },
		{181, {"Corticera", "Corticera"} },
		{182, {"Emerald Dragon", "Emerald Dragon"} },
		{183, {"Overgrowth", "Overgrowth"} },
		{184, {"Corticera", "Corticera"} },
		{185, {"Golden Koi", "Golden Koi"} },
		{186, {"Wave Spray", "Wave Spray"} },
		{187, {"Zirka", "Zirka"} },
		{188, {"Graven", "Graven"} },
		{189, {"Bright Water", "Bright Water"} },
		{190, {"Black Limba", "Black Limba"} },
		{191, {"Tempest", "Tempest"} },
		{192, {"Shattered", "Shattered"} },
		{193, {"Bone Pile", "Bone Pile"} },
		{194, {"Spitfire", "Spitfire"} },
		{195, {"Demeter", "Demeter"} },
		{196, {"Emerald", "Emerald"} },
		{197, {"Anodized Navy", "Anodized Navy"} },
		{198, {"Hazard", "Hazard"} },
		{199, {"Dry Season", "Dry Season"} },
		{200, {"Mayan Dreams", "Mayan Dreams"} },
		{201, {"Palm", "Palm"} },
		{202, {"Jungle DDPAT", "Jungle DDPAT"} },
		{203, {"Rust Coat", "Rust Coat"} },
		{204, {"Mosaico", "Mosaico"} },
		{205, {"Jungle", "Jungle"} },
		{206, {"Tornado", "Tornado"} },
		{207, {"Facets", "Facets"} },
		{208, {"Sand Dune", "Sand Dune"} },
		{209, {"Groundwater", "Groundwater"} },
		{210, {"Anodized Gunmetal", "Anodized Gunmetal"} },
		{211, {"Ocean Foam", "Ocean Foam"} },
		{212, {"Graphite", "Graphite"} },
		{213, {"Ocean Foam", "Ocean Foam"} },
		{214, {"Graphite", "Graphite"} },
		{215, {"X-Ray", "X-Ray"} },
		{216, {"Blue Titanium", "Blue Titanium"} },
		{217, {"Blood Tiger", "Blood Tiger"} },
		{218, {"Hexane", "Hexane"} },
		{219, {"Hive", "Hive"} },
		{220, {"Hemoglobin", "Hemoglobin"} },
		{221, {"Serum", "Serum"} },
		{222, {"Blood in the Water", "Blood in the Water"} },
		{223, {"Nightshade", "Nightshade"} },
		{224, {"Water Sigil", "Water Sigil"} },
		{225, {"Ghost Camo", "Ghost Camo"} },
		{226, {"Blue Laminate", "Blue Laminate"} },
		{227, {"Electric Hive", "Electric Hive"} },
		{228, {"Blind Spot", "Blind Spot"} },
		{229, {"Azure Zebra", "Azure Zebra"} },
		{230, {"Steel Disruption", "Steel Disruption"} },
		{231, {"Cobalt Disruption", "Cobalt Disruption"} },
		{232, {"Crimson Web", "Crimson Web"} },
		{233, {"Tropical Storm", "Tropical Storm"} },
		{234, {"Ash Wood", "Ash Wood"} },
		{235, {"VariCamo", "VariCamo"} },
		{236, {"Night Ops", "Night Ops"} },
		{237, {"Urban Rubble", "Urban Rubble"} },
		{238, {"VariCamo Blue", "VariCamo Blue"} },
		{240, {"CaliCamo", "CaliCamo"} },
		{241, {"Hunting Blind", "Hunting Blind"} },
		{242, {"Army Mesh", "Army Mesh"} },
		{243, {"Gator Mesh", "Gator Mesh"} },
		{244, {"Teardown", "Teardown"} },
		{245, {"Army Recon", "Army Recon"} },
		{246, {"Amber Fade", "Amber Fade"} },
		{247, {"Damascus Steel", "Damascus Steel"} },
		{248, {"Red Quartz", "Red Quartz"} },
		{249, {"Cobalt Quartz", "Cobalt Quartz"} },
		{250, {"Full Stop", "Full Stop"} },
		{251, {"Pit Viper", "Pit Viper"} },
		{252, {"Silver Quartz", "Silver Quartz"} },
		{253, {"Acid Fade", "Acid Fade"} },
		{254, {"Nitro", "Nitro"} },
		{255, {"Asiimov", "Asiimov"} },
		{256, {"The Kraken", "The Kraken"} },
		{257, {"Guardian", "Guardian"} },
		{258, {"Mehndi", "Mehndi"} },
		{259, {"Redline", "Redline"} },
		{260, {"Pulse", "Pulse"} },
		{261, {"Marina", "Marina"} },
		{262, {"Rose Iron", "Rose Iron"} },
		{263, {"Rising Skull", "Rising Skull"} },
		{264, {"Sandstorm", "Sandstorm"} },
		{265, {"Kami", "Kami"} },
		{266, {"Magma", "Magma"} },
		{267, {"Cobalt Halftone", "Cobalt Halftone"} },
		{268, {"Tread Plate", "Tread Plate"} },
		{269, {"The Fuschia Is Now", "The Fuschia Is Now"} },
		{270, {"Victoria", "Victoria"} },
		{271, {"Undertow", "Undertow"} },
		{272, {"Titanium Bit", "Titanium Bit"} },
		{273, {"Heirloom", "Heirloom"} },
		{274, {"Copper Galaxy", "Copper Galaxy"} },
		{275, {"Red FragCam", "Red FragCam"} },
		{276, {"Panther", "Panther"} },
		{277, {"Stainless", "Stainless"} },
		{278, {"Blue Fissure", "Blue Fissure"} },
		{279, {"Asiimov", "Asiimov"} },
		{280, {"Chameleon", "Chameleon"} },
		{281, {"Corporal", "Corporal"} },
		{282, {"Redline", "Redline"} },
		{283, {"Trigon", "Trigon"} },
		{284, {"Heat", "Heat"} },
		{285, {"Terrain", "Terrain"} },
		{286, {"Antique", "Antique"} },
		{287, {"Pulse", "Pulse"} },
		{288, {"Sergeant", "Sergeant"} },
		{289, {"Sandstorm", "Sandstorm"} },
		{290, {"Guardian", "Guardian"} },
		{291, {"Heaven Guard", "Heaven Guard"} },
		{293, {"Death Rattle", "Death Rattle"} },
		{294, {"Green Apple", "Green Apple"} },
		{295, {"Franklin", "Franklin"} },
		{296, {"Meteorite", "Meteorite"} },
		{297, {"Tuxedo", "Tuxedo"} },
		{298, {"Army Sheen", "Army Sheen"} },
		{299, {"Caged Steel", "Caged Steel"} },
		{300, {"Emerald Pinstripe", "Emerald Pinstripe"} },
		{301, {"Atomic Alloy", "Atomic Alloy"} },
		{302, {"Vulcan", "Vulcan"} },
		{303, {"Isaac", "Isaac"} },
		{304, {"Slashed", "Slashed"} },
		{305, {"Torque", "Torque"} },
		{306, {"Antique", "Antique"} },
		{307, {"Retribution", "Retribution"} },
		{308, {"Kami", "Kami"} },
		{309, {"Howl", "Howl"} },
		{310, {"Curse", "Curse"} },
		{311, {"Desert Warfare", "Desert Warfare"} },
		{312, {"Cyrex", "Cyrex"} },
		{313, {"Orion", "Orion"} },
		{314, {"Heaven Guard", "Heaven Guard"} },
		{315, {"Poison Dart", "Poison Dart"} },
		{316, {"Jaguar", "Jaguar"} },
		{317, {"Bratatat", "Bratatat"} },
		{318, {"Road Rash", "Road Rash"} },
		{319, {"Detour", "Detour"} },
		{320, {"Red Python", "Red Python"} },
		{321, {"Master Piece", "Master Piece"} },
		{322, {"Nitro", "Nitro"} },
		{323, {"Rust Coat", "Rust Coat"} },
		{325, {"Chalice", "Chalice"} },
		{326, {"Knight", "Knight"} },
		{327, {"Chainmail", "Chainmail"} },
		{328, {"Hand Cannon", "Hand Cannon"} },
		{329, {"Dark Age", "Dark Age"} },
		{330, {"Briar", "Briar"} },
		{332, {"Royal Blue", "Royal Blue"} },
		{333, {"Indigo", "Indigo"} },
		{334, {"Twist", "Twist"} },
		{335, {"Module", "Module"} },
		{336, {"Desert-Strike", "Desert-Strike"} },
		{337, {"Tatter", "Tatter"} },
		{338, {"Pulse", "Pulse"} },
		{339, {"Caiman", "Caiman"} },
		{340, {"Jet Set", "Jet Set"} },
		{341, {"First Class", "First Class"} },
		{342, {"Leather", "Leather"} },
		{343, {"Commuter", "Commuter"} },
		{344, {"Dragon Lore", "Dragon Lore"} },
		{345, {"First Class", "First Class"} },
		{346, {"Coach Class", "Coach Class"} },
		{347, {"Pilot", "Pilot"} },
		{348, {"Red Leather", "Red Leather"} },
		{349, {"Osiris", "Osiris"} },
		{350, {"Tigris", "Tigris"} },
		{351, {"Conspiracy", "Conspiracy"} },
		{352, {"Fowl Play", "Fowl Play"} },
		{353, {"Water Elemental", "Water Elemental"} },
		{354, {"Urban Hazard", "Urban Hazard"} },
		{355, {"Desert-Strike", "Desert-Strike"} },
		{356, {"Koi", "Koi"} },
		{357, {"Ivory", "Ivory"} },
		{358, {"Supernova", "Supernova"} },
		{359, {"Asiimov", "Asiimov"} },
		{360, {"Cyrex", "Cyrex"} },
		{361, {"Abyss", "Abyss"} },
		{362, {"Labyrinth", "Labyrinth"} },
		{363, {"Traveler", "Traveler"} },
		{364, {"Business Class", "Business Class"} },
		{365, {"Olive Plaid", "Olive Plaid"} },
		{366, {"Green Plaid", "Green Plaid"} },
		{367, {"Reactor", "Reactor"} },
		{368, {"Setting Sun", "Setting Sun"} },
		{369, {"Nuclear Waste", "Nuclear Waste"} },
		{370, {"Bone Machine", "Bone Machine"} },
		{371, {"Styx", "Styx"} },
		{372, {"Nuclear Garden", "Nuclear Garden"} },
		{373, {"Contamination", "Contamination"} },
		{374, {"Toxic", "Toxic"} },
		{375, {"Radiation Hazard", "Radiation Hazard"} },
		{376, {"Chemical Green", "Chemical Green"} },
		{377, {"Hot Shot", "Hot Shot"} },
		{378, {"Fallout Warning", "Fallout Warning"} },
		{379, {"Cerberus", "Cerberus"} },
		{380, {"Wasteland Rebel", "Wasteland Rebel"} },
		{381, {"Grinder", "Grinder"} },
		{382, {"Murky", "Murky"} },
		{383, {"Basilisk", "Basilisk"} },
		{384, {"Griffin", "Griffin"} },
		{385, {"Firestarter", "Firestarter"} },
		{386, {"Dart", "Dart"} },
		{387, {"Urban Hazard", "Urban Hazard"} },
		{388, {"Cartel", "Cartel"} },
		{389, {"Fire Elemental", "Fire Elemental"} },
		{390, {"Highwayman", "Highwayman"} },
		{391, {"Cardiac", "Cardiac"} },
		{392, {"Delusion", "Delusion"} },
		{393, {"Tranquility", "Tranquility"} },
		{394, {"Cartel", "Cartel"} },
		{395, {"Man-o-war", "Man-o-war"} },
		{396, {"Urban Shock", "Urban Shock"} },
		{397, {"Naga", "Naga"} },
		{398, {"Chatterbox", "Chatterbox"} },
		{399, {"Catacombs", "Catacombs"} },
		{400, {"龍王 (Dragon King)", "龍王 (Dragon King)"} },
		{401, {"System Lock", "System Lock"} },
		{402, {"Malachite", "Malachite"} },
		{403, {"Deadly Poison", "Deadly Poison"} },
		{404, {"Muertos", "Muertos"} },
		{405, {"Serenity", "Serenity"} },
		{406, {"Grotto", "Grotto"} },
		{407, {"Quicksilver", "Quicksilver"} },
		{409, {"Tiger Tooth", "Tiger Tooth"} },
		{410, {"Damascus Steel", "Damascus Steel"} },
		{411, {"Damascus Steel", "Damascus Steel"} },
		{413, {"Marble Fade", "Marble Fade"} },
		{414, {"Rust Coat", "Rust Coat"} },
		{415, {"Doppler", "Doppler"} },
		{416, {"Doppler", "Doppler"} },
		{417, {"Doppler", "Doppler"} },
		{418, {"Doppler", "Doppler"} },
		{419, {"Doppler", "Doppler"} },
		{420, {"Doppler", "Doppler"} },
		{421, {"Doppler", "Doppler"} },
		{422, {"Elite Build", "Elite Build"} },
		{423, {"Armor Core", "Armor Core"} },
		{424, {"Worm God", "Worm God"} },
		{425, {"Bronze Deco", "Bronze Deco"} },
		{426, {"Valence", "Valence"} },
		{427, {"Monkey Business", "Monkey Business"} },
		{428, {"Eco", "Eco"} },
		{429, {"Djinn", "Djinn"} },
		{430, {"Hyper Beast", "Hyper Beast"} },
		{431, {"Heat", "Heat"} },
		{432, {"Man-o-war", "Man-o-war"} },
		{433, {"Neon Rider", "Neon Rider"} },
		{434, {"Origami", "Origami"} },
		{435, {"Pole Position", "Pole Position"} },
		{436, {"Grand Prix", "Grand Prix"} },
		{437, {"Twilight Galaxy", "Twilight Galaxy"} },
		{438, {"Chronos", "Chronos"} },
		{439, {"Hades", "Hades"} },
		{440, {"Icarus Fell", "Icarus Fell"} },
		{441, {"Minotaurs Labyrinth", "Minotaurs Labyrinth"} },
		{442, {"Asterion", "Asterion"} },
		{443, {"Pathfinder", "Pathfinder"} },
		{444, {"Daedalus", "Daedalus"} },
		{445, {"Hot Rod", "Hot Rod"} },
		{446, {"Medusa", "Medusa"} },
		{447, {"Duelist", "Duelist"} },
		{448, {"Pandoras Box", "Pandoras Box"} },
		{449, {"Poseidon", "Poseidon"} },
		{450, {"Moon in Libra", "Moon in Libra"} },
		{451, {"Sun in Leo", "Sun in Leo"} },
		{452, {"Shipping Forecast", "Shipping Forecast"} },
		{453, {"Emerald", "Emerald"} },
		{454, {"Para Green", "Para Green"} },
		{455, {"Akihabara Accept", "Akihabara Accept"} },
		{456, {"Hydroponic", "Hydroponic"} },
		{457, {"Bamboo Print", "Bamboo Print"} },
		{458, {"Bamboo Shadow", "Bamboo Shadow"} },
		{459, {"Bamboo Forest", "Bamboo Forest"} },
		{460, {"Aqua Terrace", "Aqua Terrace"} },
		{462, {"Counter Terrace", "Counter Terrace"} },
		{463, {"Terrace", "Terrace"} },
		{464, {"Neon Kimono", "Neon Kimono"} },
		{465, {"Orange Kimono", "Orange Kimono"} },
		{466, {"Crimson Kimono", "Crimson Kimono"} },
		{467, {"Mint Kimono", "Mint Kimono"} },
		{468, {"Midnight Storm", "Midnight Storm"} },
		{469, {"Sunset Storm 壱", "Sunset Storm 壱"} },
		{470, {"Sunset Storm 弐", "Sunset Storm 弐"} },
		{471, {"Daybreak", "Daybreak"} },
		{472, {"Impact Drill", "Impact Drill"} },
		{473, {"Seabird", "Seabird"} },
		{474, {"Aquamarine Revenge", "Aquamarine Revenge"} },
		{475, {"Hyper Beast", "Hyper Beast"} },
		{476, {"Yellow Jacket", "Yellow Jacket"} },
		{477, {"Neural Net", "Neural Net"} },
		{478, {"Rocket Pop", "Rocket Pop"} },
		{479, {"Bunsen Burner", "Bunsen Burner"} },
		{480, {"Evil Daimyo", "Evil Daimyo"} },
		{481, {"Nemesis", "Nemesis"} },
		{482, {"Ruby Poison Dart", "Ruby Poison Dart"} },
		{483, {"Loudmouth", "Loudmouth"} },
		{484, {"Ranger", "Ranger"} },
		{485, {"Handgun", "Handgun"} },
		{486, {"Elite Build", "Elite Build"} },
		{487, {"Cyrex", "Cyrex"} },
		{488, {"Riot", "Riot"} },
		{489, {"Torque", "Torque"} },
		{490, {"Frontside Misty", "Frontside Misty"} },
		{491, {"Dualing Dragons", "Dualing Dragons"} },
		{492, {"Survivor Z", "Survivor Z"} },
		{493, {"Flux", "Flux"} },
		{494, {"Stone Cold", "Stone Cold"} },
		{495, {"Wraiths", "Wraiths"} },
		{496, {"Nebula Crusader", "Nebula Crusader"} },
		{497, {"Golden Coil", "Golden Coil"} },
		{498, {"Rangeen", "Rangeen"} },
		{499, {"Cobalt Core", "Cobalt Core"} },
		{500, {"Special Delivery", "Special Delivery"} },
		{501, {"Wingshot", "Wingshot"} },
		{502, {"Green Marine", "Green Marine"} },
		{503, {"Big Iron", "Big Iron"} },
		{504, {"Kill Confirmed", "Kill Confirmed"} },
		{505, {"Scumbria", "Scumbria"} },
		{506, {"Point Disarray", "Point Disarray"} },
		{507, {"Ricochet", "Ricochet"} },
		{508, {"Fuel Rod", "Fuel Rod"} },
		{509, {"Corinthian", "Corinthian"} },
		{510, {"Retrobution", "Retrobution"} },
		{511, {"The Executioner", "The Executioner"} },
		{512, {"Royal Paladin", "Royal Paladin"} },
		{514, {"Power Loader", "Power Loader"} },
		{515, {"Imperial", "Imperial"} },
		{516, {"Shapewood", "Shapewood"} },
		{517, {"Yorick", "Yorick"} },
		{518, {"Outbreak", "Outbreak"} },
		{519, {"Tiger Moth", "Tiger Moth"} },
		{520, {"Avalanche", "Avalanche"} },
		{521, {"Teclu Burner", "Teclu Burner"} },
		{522, {"Fade", "Fade"} },
		{523, {"Amber Fade", "Amber Fade"} },
		{524, {"Fuel Injector", "Fuel Injector"} },
		{525, {"Elite Build", "Elite Build"} },
		{526, {"Photic Zone", "Photic Zone"} },
		{527, {"Kumicho Dragon", "Kumicho Dragon"} },
		{528, {"Cartel", "Cartel"} },
		{529, {"Valence", "Valence"} },
		{530, {"Triumvirate", "Triumvirate"} },
		{532, {"Royal Legion", "Royal Legion"} },
		{533, {"The Battlestar", "The Battlestar"} },
		{534, {"Lapis Gator", "Lapis Gator"} },
		{535, {"Praetorian", "Praetorian"} },
		{536, {"Impire", "Impire"} },
		{537, {"Hyper Beast", "Hyper Beast"} },
		{538, {"Necropos", "Necropos"} },
		{539, {"Jambiya", "Jambiya"} },
		{540, {"Lead Conduit", "Lead Conduit"} },
		{541, {"Fleet Flock", "Fleet Flock"} },
		{542, {"Judgement of Anubis", "Judgement of Anubis"} },
		{543, {"Red Astor", "Red Astor"} },
		{544, {"Ventilators", "Ventilators"} },
		{545, {"Orange Crash", "Orange Crash"} },
		{546, {"Firefight", "Firefight"} },
		{547, {"Spectre", "Spectre"} },
		{548, {"Chanticos Fire", "Chanticos Fire"} },
		{549, {"Bioleak", "Bioleak"} },
		{550, {"Oceanic", "Oceanic"} },
		{551, {"Asiimov", "Asiimov"} },
		{552, {"Fubar", "Fubar"} },
		{553, {"Atlas", "Atlas"} },
		{554, {"Ghost Crusader", "Ghost Crusader"} },
		{555, {"Re-Entry", "Re-Entry"} },
		{556, {"Primal Saber", "Primal Saber"} },
		{557, {"Black Tie", "Black Tie"} },
		{558, {"Lore", "Lore"} },
		{559, {"Lore", "Lore"} },
		{560, {"Lore", "Lore"} },
		{561, {"Lore", "Lore"} },
		{562, {"Lore", "Lore"} },
		{563, {"Black Laminate", "Black Laminate"} },
		{564, {"Black Laminate", "Black Laminate"} },
		{565, {"Black Laminate", "Black Laminate"} },
		{566, {"Black Laminate", "Black Laminate"} },
		{567, {"Black Laminate", "Black Laminate"} },
		{568, {"Gamma Doppler", "Gamma Doppler"} },
		{569, {"Gamma Doppler", "Gamma Doppler"} },
		{570, {"Gamma Doppler", "Gamma Doppler"} },
		{571, {"Gamma Doppler", "Gamma Doppler"} },
		{572, {"Gamma Doppler", "Gamma Doppler"} },
		{573, {"Autotronic", "Autotronic"} },
		{574, {"Autotronic", "Autotronic"} },
		{575, {"Autotronic", "Autotronic"} },
		{576, {"Autotronic", "Autotronic"} },
		{577, {"Autotronic", "Autotronic"} },
		{578, {"Bright Water", "Bright Water"} },
		{579, {"Bright Water", "Bright Water"} },
		{580, {"Freehand", "Freehand"} },
		{581, {"Freehand", "Freehand"} },
		{582, {"Freehand", "Freehand"} },
		{583, {"Aristocrat", "Aristocrat"} },
		{584, {"Phobos", "Phobos"} },
		{585, {"Violent Daimyo", "Violent Daimyo"} },
		{586, {"Wasteland Rebel", "Wasteland Rebel"} },
		{587, {"Mecha Industries", "Mecha Industries"} },
		{588, {"Desolate Space", "Desolate Space"} },
		{589, {"Carnivore", "Carnivore"} },
		{590, {"Exo", "Exo"} },
		{591, {"Imperial Dragon", "Imperial Dragon"} },
		{592, {"Iron Clad", "Iron Clad"} },
		{593, {"Chopper", "Chopper"} },
		{594, {"Harvester", "Harvester"} },
		{595, {"Reboot", "Reboot"} },
		{596, {"Limelight", "Limelight"} },
		{597, {"Bloodsport", "Bloodsport"} },
		{598, {"Aerial", "Aerial"} },
		{599, {"Ice Cap", "Ice Cap"} },
		{600, {"Neon Revolution", "Neon Revolution"} },
		{601, {"Syd Mead", "Syd Mead"} },
		{602, {"Imprint", "Imprint"} },
		{603, {"Directive", "Directive"} },
		{604, {"Roll Cage", "Roll Cage"} },
		{605, {"Scumbria", "Scumbria"} },
		{606, {"Ventilator", "Ventilator"} },
		{607, {"Weasel", "Weasel"} },
		{608, {"Petroglyph", "Petroglyph"} },
		{609, {"Airlock", "Airlock"} },
		{610, {"Dazzle", "Dazzle"} },
		{611, {"Grim", "Grim"} },
		{612, {"Powercore", "Powercore"} },
		{613, {"Triarch", "Triarch"} },
		{614, {"Fuel Injector", "Fuel Injector"} },
		{615, {"Briefing", "Briefing"} },
		{616, {"Slipstream", "Slipstream"} },
		{617, {"Doppler", "Doppler"} },
		{618, {"Doppler", "Doppler"} },
		{619, {"Doppler", "Doppler"} },
		{620, {"Ultraviolet", "Ultraviolet"} },
		{621, {"Ultraviolet", "Ultraviolet"} },
		{622, {"Polymer", "Polymer"} },
		{623, {"Ironwork", "Ironwork"} },
		{624, {"Dragonfire", "Dragonfire"} },
		{625, {"Royal Consorts", "Royal Consorts"} },
		{626, {"Mecha Industries", "Mecha Industries"} },
		{627, {"Cirrus", "Cirrus"} },
		{628, {"Stinger", "Stinger"} },
		{629, {"Black Sand", "Black Sand"} },
		{630, {"Sand Scale", "Sand Scale"} },
		{631, {"Flashback", "Flashback"} },
		{632, {"Buzz Kill", "Buzz Kill"} },
		{633, {"Sonar", "Sonar"} },
		{634, {"Gila", "Gila"} },
		{635, {"Turf", "Turf"} },
		{636, {"Shallow Grave", "Shallow Grave"} },
		{637, {"Cyrex", "Cyrex"} },
		{638, {"Wasteland Princess", "Wasteland Princess"} },
		{639, {"Bloodsport", "Bloodsport"} },
		{640, {"Fever Dream", "Fever Dream"} },
		{641, {"Jungle Slipstream", "Jungle Slipstream"} },
		{642, {"Blueprint", "Blueprint"} },
		{643, {"Xiangliu", "Xiangliu"} },
		{644, {"Decimator", "Decimator"} },
		{645, {"Oxide Blaze", "Oxide Blaze"} },
		{646, {"Capillary", "Capillary"} },
		{647, {"Crimson Tsunami", "Crimson Tsunami"} },
		{648, {"Emerald Poison Dart", "Emerald Poison Dart"} },
		{649, {"Akoben", "Akoben"} },
		{650, {"Ripple", "Ripple"} },
		{651, {"Last Dive", "Last Dive"} },
		{652, {"Scaffold", "Scaffold"} },
		{653, {"Neo-Noir", "Neo-Noir"} },
		{654, {"Seasons", "Seasons"} },
		{655, {"Zander", "Zander"} },
		{656, {"Orbit Mk01", "Orbit Mk01"} },
		{657, {"Blueprint", "Blueprint"} },
		{658, {"Cobra Strike", "Cobra Strike"} },
		{659, {"Macabre", "Macabre"} },
		{660, {"Hyper Beast", "Hyper Beast"} },
		{661, {"Sugar Rush", "Sugar Rush"} },
		{662, {"Oni Taiji", "Oni Taiji"} },
		{663, {"Briefing", "Briefing"} },
		{664, {"Hellfire", "Hellfire"} },
		{665, {"Aloha", "Aloha"} },
		{666, {"Hard Water", "Hard Water"} },
		{667, {"Woodsman", "Woodsman"} },
		{668, {"Red Rock", "Red Rock"} },
		{669, {"Death Grip", "Death Grip"} },
		{670, {"Deaths Head", "Deaths Head"} },
		{671, {"Cut Out", "Cut Out"} },
		{672, {"Metal Flowers", "Metal Flowers"} },
		{673, {"Morris", "Morris"} },
		{674, {"Triqua", "Triqua"} },
		{675, {"The Empress", "The Empress"} },
		{676, {"High Roller", "High Roller"} },
		{677, {"Hunter", "Hunter"} },
		{678, {"See Ya Later", "See Ya Later"} },
		{679, {"Goo", "Goo"} },
		{680, {"Off World", "Off World"} },
		{681, {"Leaded Glass", "Leaded Glass"} },
		{682, {"Oceanic", "Oceanic"} },
		{683, {"Llama Cannon", "Llama Cannon"} },
		{684, {"Cracked Opal", "Cracked Opal"} },
		{685, {"Jungle Slipstream", "Jungle Slipstream"} },
		{686, {"Phantom", "Phantom"} },
		{687, {"Tacticat", "Tacticat"} },
		{688, {"Exposure", "Exposure"} },
		{689, {"Ziggy", "Ziggy"} },
		{690, {"Stymphalian", "Stymphalian"} },
		{691, {"Mortis", "Mortis"} },
		{692, {"Night Riot", "Night Riot"} },
		{693, {"Flame Test", "Flame Test"} },
		{694, {"Moonrise", "Moonrise"} },
		{695, {"Neo-Noir", "Neo-Noir"} },
		{696, {"Bloodsport", "Bloodsport"} },
		{697, {"Black Sand", "Black Sand"} },
		{698, {"Lionfish", "Lionfish"} },
		{699, {"Wild Six", "Wild Six"} },
		{700, {"Urban Hazard", "Urban Hazard"} },
		{701, {"Grip", "Grip"} },
		{702, {"Aloha", "Aloha"} },
		{703, {"SWAG-7", "SWAG-7"} },
		{704, {"Arctic Wolf", "Arctic Wolf"} },
		{705, {"Cortex", "Cortex"} },
		{706, {"Oxide Blaze", "Oxide Blaze"} },
		{707, {"Neon Rider", "Neon Rider"} },
		{708, {"Amber Slipstream", "Amber Slipstream"} },
		{709, {"Eco", "Eco"} },
		{710, {"Shred", "Shred"} },
		{711, {"Code Red", "Code Red"} },
		{712, {"High Seas", "High Seas"} },
		{713, {"Warhawk", "Warhawk"} },
		{714, {"Nightmare", "Nightmare"} },
		{715, {"Capillary", "Capillary"} },
		{716, {"Toy Soldier", "Toy Soldier"} },
		{717, {"Traction", "Traction"} },
		{718, {"PAW", "PAW"} },
		{719, {"Powercore", "Powercore"} },
		{720, {"Devourer", "Devourer"} },
		{721, {"Survivalist", "Survivalist"} },
		{722, {"Snek-9", "Snek-9"} },
		{723, {"Eye of Athena", "Eye of Athena"} },
		{724, {"Wild Lotus", "Wild Lotus"} },
		{725, {"Day Lily", "Day Lily"} },
		{726, {"Sunset Lily", "Sunset Lily"} },
		{727, {"Midnight Lily", "Midnight Lily"} },
		{728, {"Teal Blossom", "Teal Blossom"} },
		{729, {"Crimson Blossom", "Crimson Blossom"} },
		{730, {"Dark Blossom", "Dark Blossom"} },
		{731, {"Banana Leaf", "Banana Leaf"} },
		{732, {"Synth Leaf", "Synth Leaf"} },
		{733, {"Rust Leaf", "Rust Leaf"} },
		{734, {"Wild Lily", "Wild Lily"} },
		{735, {"Night Stripe", "Night Stripe"} },
		{736, {"The Prince", "The Prince"} },
		{737, {"Cinquedea", "Cinquedea"} },
		{738, {"Orange Murano", "Orange Murano"} },
		{739, {"Violet Murano", "Violet Murano"} },
		{740, {"Navy Murano", "Navy Murano"} },
		{741, {"Dark Filigree", "Dark Filigree"} },
		{742, {"Red Filigree", "Red Filigree"} },
		{743, {"Orange Filigree", "Orange Filigree"} },
		{744, {"Baroque Red", "Baroque Red"} },
		{745, {"Baroque Purple", "Baroque Purple"} },
		{746, {"Baroque Orange", "Baroque Orange"} },
		{747, {"Twin Turbo", "Twin Turbo"} },
		{748, {"Calf Skin", "Calf Skin"} },
		{749, {"Vino Primo", "Vino Primo"} },
		{750, {"Integrale", "Integrale"} },
		{751, {"Hand Brake", "Hand Brake"} },
		{752, {"Fade", "Fade"} },
		{753, {"Dirt Drop", "Dirt Drop"} },
		{754, {"Rust Coat", "Rust Coat"} },
		{755, {"Slide", "Slide"} },
		{756, {"Gungnir", "Gungnir"} },
		{757, {"Emerald Jörmungandr", "Emerald Jörmungandr"} },
		{758, {"Flame Jörmungandr", "Flame Jörmungandr"} },
		{759, {"Astral Jörmungandr", "Astral Jörmungandr"} },
		{760, {"Frost Borre", "Frost Borre"} },
		{761, {"Copper Borre", "Copper Borre"} },
		{762, {"Red Stone", "Red Stone"} },
		{763, {"Mjölnir", "Mjölnir"} },
		{775, {"Facility Sketch", "Facility Sketch"} },
		{776, {"Facility Negative", "Facility Negative"} },
		{777, {"Facility Draft", "Facility Draft"} },
		{778, {"Facility Dark", "Facility Dark"} },
		{779, {"Random Access", "Random Access"} },
		{780, {"Mainframe", "Mainframe"} },
		{781, {"Co-Processor", "Co-Processor"} },
		{782, {"Motherboard", "Motherboard"} },
		{783, {"Bulkhead", "Bulkhead"} },
		{784, {"Coolant", "Coolant"} },
		{785, {"Mandrel", "Mandrel"} },
		{786, {"Exchanger", "Exchanger"} },
		{787, {"Core Breach", "Core Breach"} },
		{788, {"Acheron", "Acheron"} },
		{789, {"Nuclear Garden", "Nuclear Garden"} },
		{790, {"Cold Fusion", "Cold Fusion"} },
		{791, {"Remote Control", "Remote Control"} },
		{792, {"Control Panel", "Control Panel"} },
		{793, {"Converter", "Converter"} },
		{794, {"Sweeper", "Sweeper"} },
		{795, {"Safety Net", "Safety Net"} },
		{796, {"Check Engine", "Check Engine"} },
		{797, {"Brake Light", "Brake Light"} },
		{798, {"Nitro", "Nitro"} },
		{799, {"High Beam", "High Beam"} },
		{800, {"Lab Rats", "Lab Rats"} },
		{801, {"Asiimov", "Asiimov"} },
		{802, {"Momentum", "Momentum"} },
		{803, {"Neo-Noir", "Neo-Noir"} },
		{804, {"Modest Threat", "Modest Threat"} },
		{805, {"Mecha Industries", "Mecha Industries"} },
		{806, {"Scavenger", "Scavenger"} },
		{807, {"Signal", "Signal"} },
		{808, {"Oxide Blaze", "Oxide Blaze"} },
		{809, {"Wood Fired", "Wood Fired"} },
		{810, {"Phosphor", "Phosphor"} },
		{811, {"Magnesium", "Magnesium"} },
		{812, {"Pipe Down", "Pipe Down"} },
		{813, {"Nevermore", "Nevermore"} },
		{814, {"Black Sand", "Black Sand"} },
		{815, {"Danger Close", "Danger Close"} },
		{816, {"Fubar", "Fubar"} },
		{817, {"Flashback", "Flashback"} },
		{835, {"Crypsis", "Crypsis"} },
		{836, {"Uncharted", "Uncharted"} },
		{837, {"Angry Mob", "Angry Mob"} },
		{838, {"Atheris", "Atheris"} },
		{839, {"Bamboozle", "Bamboozle"} },
		{840, {"Whitefish", "Whitefish"} },
		{841, {"Light Rail", "Light Rail"} },
		{842, {"Akoben", "Akoben"} },
		{843, {"Skull Crusher", "Skull Crusher"} },
		{844, {"The Emperor", "The Emperor"} },
		{845, {"Momentum", "Momentum"} },
		{846, {"Gauss", "Gauss"} },
		{847, {"Mischief", "Mischief"} },
		{848, {"Verdigris", "Verdigris"} },
		{849, {"Off World", "Off World"} },
		{850, {"Incinegator", "Incinegator"} },
		{851, {"Moonrise", "Moonrise"} },
		{852, {"Doppler", "Doppler"} },
		{853, {"Doppler", "Doppler"} },
		{854, {"Doppler", "Doppler"} },
		{855, {"Doppler", "Doppler"} },
		{856, {"Marble Fade", "Marble Fade"} },
		{857, {"Damascus Steel", "Damascus Steel"} },
		{858, {"Damascus Steel", "Damascus Steel"} },
		{859, {"Emerald Quartz", "Emerald Quartz"} },
		{860, {"Pyre", "Pyre"} },
		{861, {"Barricade", "Barricade"} },
		{862, {"Moss Quartz", "Moss Quartz"} },
		{863, {"Night Borre", "Night Borre"} },
		{864, {"Candy Apple", "Candy Apple"} },
		{865, {"Stone Mosaico", "Stone Mosaico"} },
		{866, {"Canal Spray", "Canal Spray"} },
		{867, {"Stained Glass", "Stained Glass"} },
		{868, {"Sea Calico", "Sea Calico"} },
		{869, {"Sundown", "Sundown"} },
		{870, {"Jungle Thicket", "Jungle Thicket"} },
		{871, {"Surfwood", "Surfwood"} },
		{872, {"Bamboo Garden", "Bamboo Garden"} },
		{873, {"Seabird", "Seabird"} },
		{884, {"Embargo", "Embargo"} },
		{885, {"Rat Rod", "Rat Rod"} },
		{886, {"Arctic Wolf", "Arctic Wolf"} },
		{887, {"Containment Breach", "Containment Breach"} },
		{888, {"Acid Wash", "Acid Wash"} },
		{889, {"Decimator", "Decimator"} },
		{890, {"Plume", "Plume"} },
		{891, {"Black Sand", "Black Sand"} },
		{892, {"Memento", "Memento"} },
		{893, {"Neon Ply", "Neon Ply"} },
		{894, {"Obsidian", "Obsidian"} },
		{895, {"Balance", "Balance"} },
		{896, {"Torn", "Torn"} },
		{897, {"Colony IV", "Colony IV"} },
		{898, {"Stalker", "Stalker"} },
		{899, {"Bloodshot", "Bloodshot"} },
		{900, {"Warbird", "Warbird"} },
		{902, {"Aztec", "Aztec"} },
		{903, {"Elite 1.6", "Elite 1.6"} },
		{904, {"Decommissioned", "Decommissioned"} },
		{905, {"Flash Out", "Flash Out"} },
		{906, {"Buddy", "Buddy"} },
		{907, {"Inferno", "Inferno"} },
		{908, {"Classic Crate", "Classic Crate"} },
		{909, {"Popdog", "Popdog"} },
		{910, {"Hydra", "Hydra"} },
		{911, {"Nostalgia", "Nostalgia"} },
		{913, {"Death by Puppy", "Death by Puppy"} },
		{914, {"Assault", "Assault"} },
		{915, {"Agent", "Agent"} },
		{916, {"Plastique", "Plastique"} },
		{917, {"Wildfire", "Wildfire"} },
		{918, {"Sacrifice", "Sacrifice"} },
		{919, {"Commemoration", "Commemoration"} },
		{920, {"Boroque Sand", "Boroque Sand"} },
		{941, {"Phantom Disruptor", "Phantom Disruptor"} },
		{942, {"Tom Cat", "Tom Cat"} },
		{943, {"Capillary", "Capillary"} },
		{944, {"Distressed", "Distressed"} },
		{945, {"Blue Ply", "Blue Ply"} },
		{946, {"Player Two", "Player Two"} },
		{947, {"Disco Tech", "Disco Tech"} },
		{948, {"Justice", "Justice"} },
		{949, {"Desert Strike", "Desert Strike"} },
		{950, {"Prototype", "Prototype"} },
		{951, {"Acid Etched", "Acid Etched"} },
		{952, {"Bone Forged", "Bone Forged"} },
		{953, {"Apocalypto", "Apocalypto"} },
		{954, {"Enforcer", "Enforcer"} },
		{955, {"Darkwing", "Darkwing"} },
		{956, {"Fever Dream", "Fever Dream"} },
		{957, {"Bullet Queen", "Bullet Queen"} },
		{10006, {"Charred", "Charred"} },
		{10007, {"Snakebite", "Snakebite"} },
		{10008, {"Bronzed", "Bronzed"} },
		{10009, {"Leather", "Leather"} },
		{10010, {"Spruce DDPAT", "Spruce DDPAT"} },
		{10013, {"Lunar Weave", "Lunar Weave"} },
		{10015, {"Convoy", "Convoy"} },
		{10016, {"Crimson Weave", "Crimson Weave"} },
		{10018, {"Superconductor", "Superconductor"} },
		{10019, {"Arid", "Arid"} },
		{10021, {"Slaughter", "Slaughter"} },
		{10024, {"Eclipse", "Eclipse"} },
		{10026, {"Spearmint", "Spearmint"} },
		{10027, {"Boom!", "Boom!"} },
		{10028, {"Cool Mint", "Cool Mint"} },
		{10030, {"Forest DDPAT", "Forest DDPAT"} },
		{10033, {"Crimson Kimono", "Crimson Kimono"} },
		{10034, {"Emerald Web", "Emerald Web"} },
		{10035, {"Foundation", "Foundation"} },
		{10036, {"Badlands", "Badlands"} },
		{10037, {"Pandoras Box", "Pandoras Box"} },
		{10038, {"Hedge Maze", "Hedge Maze"} },
		{10039, {"Guerrilla", "Guerrilla"} },
		{10040, {"Diamondback", "Diamondback"} },
		{10041, {"King Snake", "King Snake"} },
		{10042, {"Imperial Plaid", "Imperial Plaid"} },
		{10043, {"Overtake", "Overtake"} },
		{10044, {"Racing Green", "Racing Green"} },
		{10045, {"Amphibious", "Amphibious"} },
		{10046, {"Bronze Morph", "Bronze Morph"} },
		{10047, {"Omega", "Omega"} },
		{10048, {"Vice", "Vice"} },
		{10049, {"POW!", "POW!"} },
		{10050, {"Turtle", "Turtle"} },
		{10051, {"Transport", "Transport"} },
		{10052, {"Polygon", "Polygon"} },
		{10053, {"Cobalt Skulls", "Cobalt Skulls"} },
		{10054, {"Overprint", "Overprint"} },
		{10055, {"Duct Tape", "Duct Tape"} },
		{10056, {"Arboreal", "Arboreal"} },
		{10057, {"Emerald", "Emerald"} },
		{10058, {"Mangrove", "Mangrove"} },
		{10059, {"Rattler", "Rattler"} },
		{10060, {"Case Hardened", "Case Hardened"} },
		{10061, {"Crimson Web", "Crimson Web"} },
		{10062, {"Buckshot", "Buckshot"} },
		{10063, {"Fade", "Fade"} },
		{10064, {"Mogul", "Mogul"} },
};

namespace Skins
{
	void Localize();
}
