#pragma once

#include <map>

struct PaintNames_t
{
	const char* displayName = nullptr;
	const char* paintName = nullptr;
};

const std::map<int, PaintNames_t> itemSkins = {
		{ -1, { "No Skin" } },
		{ 2, { "#PaintKit_so_olive_Tag", "olive" } },
		{ 3, { "#PaintKit_so_red_Tag", "red" } },
		{ 5, { "#PaintKit_hy_ddpat_Tag", "ddpat" } },
		{ 6, { "#PaintKit_hy_arctic_Tag", "arctic" } },
		{ 8, { "#PaintKit_hy_desert_Tag", "desert" } },
		{ 9, { "#PaintKit_hy_tiger_Tag", "tiger" } },
		{ 10, { "#PaintKit_hy_copperhead_Tag", "copperhead" } },
		{ 11, { "#PaintKit_hy_skulls_Tag", "skulls" } },
		{ 12, { "#PaintKit_hy_webs_Tag", "webs" } },
		{ 13, { "#PaintKit_hy_splatter_Tag", "splatter" } },
		{ 14, { "#PaintKit_hy_ak47lam_Tag", "ak47lam" } },
		{ 15, { "#PaintKit_hy_gelpen_Tag", "gelpen" } },
		{ 16, { "#PaintKit_hy_v_tiger_Tag", "v_tiger" } },
		{ 17, { "#PaintKit_hy_ddpat_urb_Tag", "ddpat_urb" } },
		{ 20, { "#PaintKit_hy_zombie_Tag", "zombie" } },
		{ 21, { "#PaintKit_hy_granite_Tag", "granite" } },
		{ 22, { "#PaintKit_sp_spray_Tag", "spray" } },
		{ 25, { "#PaintKit_sp_leaves_Tag", "leaves" } },
		{ 26, { "#PaintKit_sp_short_tape_Tag", "short_tape" } },
		{ 27, { "#PaintKit_sp_tape_Tag", "tape" } },
		{ 28, { "#PaintKit_an_navy_Tag", "navy" } },
		{ 30, { "#PaintKit_sp_snake_Tag", "snake" } },
		{ 32, { "#PaintKit_an_silver_Tag", "silver" } },
		{ 33, { "#PaintKit_an_red_Tag", "red" } },
		{ 34, { "#PaintKit_am_urban_Tag", "urban" } },
		{ 36, { "#PaintKit_am_ossify_Tag", "ossify" } },
		{ 37, { "#PaintKit_aa_flames_Tag", "flames" } },
		{ 38, { "#PaintKit_aa_fade_Tag", "fade" } },
		{ 39, { "#PaintKit_so_yellow_Tag", "yellow" } },
		{ 40, { "#PaintKit_so_night_Tag", "night" } },
		{ 41, { "#PaintKit_aq_copper_Tag", "copper" } },
		{ 42, { "#PaintKit_aq_blued_Tag", "blued" } },
		{ 43, { "#PaintKit_aq_forced_Tag", "forced" } },
		{ 44, { "#PaintKit_aq_oiled_Tag", "oiled" } },
		{ 46, { "#PaintKit_so_pmc_Tag", "pmc" } },
		{ 47, { "#PaintKit_so_space_marine_Tag", "space_marine" } },
		{ 48, { "#PaintKit_am_dragon_glock_Tag", "dragon_glock" } },
		{ 51, { "#PaintKit_am_lightning_awp_Tag", "lightning_awp" } },
		{ 59, { "#PaintKit_am_zebra_Tag", "zebra" } },
		{ 60, { "#PaintKit_am_zebra_dark_Tag", "zebra_dark" } },
		{ 61, { "#PaintKit_aa_vertigo_Tag", "vertigo" } },
		{ 62, { "#PaintKit_cu_spring_nova_Tag", "spring_nova" } },
		{ 67, { "#PaintKit_am_slither_p90_Tag", "slither_p90" } },
		{ 70, { "#PaintKit_am_carbon_fiber_Tag", "carbon_fiber" } },
		{ 71, { "#PaintKit_am_scorpion_p2000_Tag", "scorpion_p2000" } },
		{ 72, { "#PaintKit_sp_mesh_tan_Tag", "mesh_tan" } },
		{ 73, { "#PaintKit_hy_feathers_aug_Tag", "feathers_aug" } },
		{ 74, { "#Paintkit_hy_arctic_contrast_Tag", "arctic_contrast" } },
		{ 75, { "#PaintKit_hy_blizzard_Tag", "blizzard" } },
		{ 76, { "#PaintKit_hy_forest_winter_Tag", "forest_winter" } },
		{ 77, { "#PaintKit_hy_forest_boreal_Tag", "forest_boreal" } },
		{ 78, { "#PaintKit_hy_forest_night_Tag", "forest_night" } },
		{ 83, { "#PaintKit_hy_ddpat_orange_Tag", "ddpat_orange" } },
		{ 84, { "#PaintKit_hy_ddpat_pink_Tag", "ddpat_pink"} },
		{ 90, { "#PaintKit_hy_sediment_Tag", "sediment" } },
		{ 92, { "#PaintKit_hy_reef_rock_Tag", "reef_rock" } },
		{ 93, { "#PaintKit_so_caramel_Tag", "caramel" } },
		{ 95, { "#PaintKit_so_grassland_Tag", "grassland" } },
		{ 96, { "#PaintKit_so_moss_Tag", "moss" } },
		{ 98, { "#PaintKit_so_purple_Tag", "purple" } },
		{ 99, { "#PaintKit_so_sand_Tag", "sand" } },
		{ 100, { "#PaintKit_so_stormfront_Tag", "stormfront" } },
		{ 101, { "#PaintKit_so_tornado_Tag", "tornado" } },
		{ 102, { "#PaintKit_so_whiteout_Tag", "whiteout" } },
		{ 104, { "#PaintKit_sp_leaves_grassland_Tag", "leaves_grassland" } },
		{ 107, { "#PaintKit_sp_mesh_arctic_contrast_Tag", "mesh_arctic_contrast" } },
		{ 110, { "#PaintKit_sp_mesh_fire_Tag", "mesh_fire" } },
		{ 111, { "#PaintKit_sp_mesh_glacier_Tag", "mesh_glacier" } },
		{ 116, { "#PaintKit_sp_mesh_sand_Tag", "mesh_sand" } },
		{ 119, { "#PaintKit_sp_spray_sage_Tag", "spray_sage" } },
		{ 122, { "#PaintKit_sp_spray_jungle_Tag", "spray_jungle" } },
		{ 124, { "#PaintKit_sp_spray_sand_Tag", "spray_sand" } },
		{ 135, { "#PaintKit_sp_tape_dots_urban_Tag", "tape_dots_urban" } },
		{ 136, { "#PaintKit_sp_tape_dots_waves_Tag", "tape_dots_waves" } },
		{ 141, { "#PaintKit_sp_tape_orange_Tag", "tape_orange" } },
		{ 143, { "#PaintKit_sp_tape_urban_Tag", "tape_urban" } },
		{ 147, { "#PaintKit_sp_short_tape_jungle_Tag", "short_tape_jungle" } },
		{ 148, { "#PaintKit_sp_short_tape_sand_Tag", "short_tape_sand" } },
		{ 149, { "#PaintKit_sp_short_tape_urban_Tag", "short_tape_urban" } },
		{ 151, { "#PaintKit_so_jungle_Tag", "jungle" } },
		{ 153, { "#PaintKit_so_tangerine_Tag", "tangerine" } },
		{ 154, { "#PaintKit_cu_broken_path_famas_Tag", "broken_path_famas" } },
		{ 155, { "#PaintKit_cu_bullet_rain_m4a1_Tag", "bullet_rain_m4a1" } },
		{ 156, { "#PaintKit_cu_catskulls_p90_Tag", "catskulls_p90" } },
		{ 157, { "#PaintKit_sp_palm_Tag", "palm" } },
		{ 158, { "#PaintKit_cu_walnut_nova_Tag", "walnut_nova" } },
		{ 159, { "#PaintKit_aq_brass_Tag", "brass" } },
		{ 162, { "#PaintKit_sp_splash_p250_Tag", "splash_p250" } },
		{ 164, { "#PaintKit_hy_hunter_modern_Tag", "hunter_modern" } },
		{ 165, { "#PaintKit_hy_hunter_blaze_pink_Tag", "hunter_blaze_pink" } },
		{ 166, { "#PaintKit_hy_hunter_blaze_orange_Tag", "hunter_blaze_orange" } },
		{ 167, { "#PaintKit_sp_nukestripe_orange_Tag", "nukestripe_orange" } },
		{ 168, { "#PaintKit_sp_nukestripe_green_Tag", "nukestripe_green" } },
		{ 169, { "#PaintKit_sp_nukestripe_maroon_Tag", "nukestripe_maroon" } },
		{ 170, { "#PaintKit_sp_zebracam_Tag", "zebracam" } },
		{ 171, { "#PaintKit_sp_nukestripe_brown_Tag", "nukestripe_brown" } },
		{ 172, { "#PaintKit_hy_ak47lam_bw_Tag", "ak47lam_bw" } },
		{ 174, { "#PaintKit_hy_blam_simple_Tag", "blam_simple" } },
		{ 175, { "#PaintKit_sp_dapple_Tag", "dapple" } },
		{ 176, { "#PaintKit_sp_zebracam_bw_Tag", "zebracam_bw" } },
		{ 177, { "#PaintKit_CSGO_Icosahedron_Tag", "Icosahedron" } },
		{ 178, { "#PaintKit_CSGO_Doomkitty_Tag", "Doomkitty" } },
		{ 179, { "#PaintKit_sp_nukestripe_green_Tag", "nukestripe_green" } },
		{ 180, { "#PaintKit_cu_fireserpent_ak47_bravo_Tag", "fireserpent_ak47_bravo" } },
		{ 181, { "#PaintKit_cu_favela_Tag", "favela" } },
		{ 182, { "#PaintKit_cu_dragon_p90_bravo_Tag", "dragon_p90_bravo" } },
		{ 183, { "#PaintKit_hy_siege_bravo_Tag", "siege_bravo" } },
		{ 184, { "#PaintKit_cu_favela_Tag", "favela" } },
		{ 185, { "#PaintKit_am_scales_bravo_Tag", "scales_bravo" } },
		{ 186, { "#PaintKit_sp_spray_waves_Tag", "spray_waves" } },
		{ 187, { "#PaintKit_sp_star_bravo_Tag", "star_bravo" } },
		{ 188, { "#PaintKit_aq_etched_mac10_bravo_Tag", "etched_mac10_bravo" } },
		{ 189, { "#PaintKit_hy_ocean_Tag", "ocean" } },
		{ 190, { "#PaintKit_cu_season_elites_bravo_Tag", "season_elites_bravo" } },
		{ 191, { "#PaintKit_hy_seaside_bravo_Tag", "seaside_bravo" } },
		{ 192, { "#PaintKit_hy_crumple_bravo_Tag", "crumple_bravo" } },
		{ 193, { "#PaintKit_sp_skull_diagram_bravo_Tag", "skull_diagram_bravo" } },
		{ 194, { "#PaintKit_sp_spitfire_famas_Tag", "spitfire_famas" } },
		{ 195, { "#PaintKit_hy_bluepolygon_bravo_Tag", "bluepolygon_bravo" } },
		{ 196, { "#PaintKit_an_emerald_bravo_Tag", "emerald_bravo" } },
		{ 197, { "#PaintKit_an_navy_Tag", "navy" } },
		{ 198, { "#PaintKit_sp_hazard_Tag", "hazard" } },
		{ 199, { "#PaintKit_sp_tape_dots_Tag", "tape_dots" } },
		{ 200, { "#PaintKit_hy_mayan_dreams_bravo_Tag", "mayan_dreams_bravo" } },
		{ 201, { "#PaintKit_sp_palm_Tag", "palm" } },
		{ 202, { "#PaintKit_hy_ddpat_jungle_Tag", "ddpat_jungle" } },
		{ 203, { "#PaintKit_aq_steel_bravo_Tag", "steel_bravo" } },
		{ 204, { "#PaintKit_hy_ali_tile_bravo_Tag", "ali_tile_bravo" } },
		{ 205, { "#PaintKit_so_jungle_Tag", "jungle" } },
		{ 206, { "#PaintKit_so_tornado_Tag", "tornado" } },
		{ 207, { "#PaintKit_hy_crumple_dark_bravo_Tag", "crumple_dark_bravo" } },
		{ 208, { "#PaintKit_so_sand_Tag", "sand" } },
		{ 209, { "#PaintKit_so_olive_Tag", "olive" } },
		{ 210, { "#PaintKit_an_gunmetal_Tag", "gunmetal" } },
		{ 211, { "#PaintKit_am_ossify_blue_Tag", "ossify_blue" } },
		{ 212, { "#PaintKit_am_crumple_Tag", "crumple" } },
		{ 213, { "#PaintKit_am_ossify_blue_Tag", "ossify_blue" } },
		{ 214, { "#PaintKit_am_crumple_Tag", "crumple" } },
		{ 215, { "#PaintKit_cu_xray_m4_Tag", "xray_m4" } },
		{ 216, { "#PaintKit_an_titanium30v_Tag", "titanium30v" } },
		{ 217, { "#PaintKit_hy_redtiger_Tag", "redtiger" } },
		{ 218, { "#PaintKit_hy_bluehex_Tag", "bluehex" } },
		{ 219, { "#PaintKit_hy_redhex_Tag", "redhex" } },
		{ 220, { "#PaintKit_am_ossify_red_Tag", "ossify_red" } },
		{ 221, { "#PaintKit_am_electric_red_Tag", "electric_red" } },
		{ 222, { "#PaintKit_cu_shark_Tag", "shark" } },
		{ 223, { "#PaintKit_hy_flowers_Tag", "flowers" } },
		{ 224, { "#PaintKit_hy_water_crest_Tag", "water_crest" } },
		{ 225, { "#PaintKit_sp_camo_wood_blue_Tag", "camo_wood_blue" } },
		{ 226, { "#PaintKit_hy_ak47lam_blue_Tag", "ak47lam_blue" } },
		{ 227, { "#PaintKit_hy_hive_Tag", "hive" } },
		{ 228, { "#PaintKit_hy_modspots_Tag", "modspots" } },
		{ 229, { "#PaintKit_sp_zebracam_blue_Tag", "zebracam_blue" } },
		{ 230, { "#PaintKit_am_ddpatdense_silver_Tag", "ddpatdense_silver" } },
		{ 231, { "#PaintKit_am_ddpatdense_peacock_Tag", "ddpatdense_peacock" } },
		{ 232, { "#PaintKit_hy_webs_Tag", "webs_darker" } },
		{ 233, { "#PaintKit_sp_palm_shadow_Tag", "palm_shadow" } },
		{ 234, { "#PaintKit_sp_twigs_Tag", "twigs" } },
		{ 235, { "#PaintKit_hy_varicamo_Tag", "varicamo" } },
		{ 236, { "#PaintKit_hy_varicamo_night_Tag", "varicamo_night" } },
		{ 237, { "#PaintKit_hy_varicamo_urban_Tag", "varicamo_urban" } },
		{ 238, { "#PaintKit_hy_varicamo_blue_Tag", "varicamo_blue" } },
		{ 240, { "#PaintKit_hy_varicamo_desert_Tag", "varicamo_desert" } },
		{ 241, { "#PaintKit_sp_mesh_slashes_Tag", "mesh_slashes" } },
		{ 242, { "#PaintKit_sp_mesh_army_Tag", "mesh_army" } },
		{ 243, { "#PaintKit_sp_mesh_python_Tag", "mesh_python" } },
		{ 244, { "#PaintKit_sp_mesh_hot_and_cold_Tag", "mesh_hot_and_cold" } },
		{ 245, { "#PaintKit_sp_spray_army_Tag", "spray_army" } },

		/* Dust2 Collection */
		{ 246, { "#PaintKit_aa_fade_metallic_Tag", "p2000_amber_fade" } },
		{ 247, { "#PaintKit_aq_damascus_Tag", "sg553_damascus_steel" } },

		/* The Train Collection */
		{ 248, { "#PaintKit_am_crystallized_red_Tag", "tec9_red_quartz" } },

		/* The Lake Collection */
		{ 249, { "#PaintKit_am_crystallized_blue_Tag", "elite_cobalt_quartz" } },

		/* The Italy Collection */
		{ 250, { "#PaintKit_hy_varicamo_red_Tag", "sawedoff_full_stop" } },
		{ 251, { "#PaintKit_hy_snakeskin_Tag", "awp_pit_viper" } },

		/* The Safehous Collection */
		{ 252, { "#PaintKit_am_crystallized_silver_Tag", "fiveseven_silver_quartz" } },
		{ 253, { "#PaintKit_aa_fade_grassland_Tag", "ssg08_acid_fade" } },

		/* The Overpass Collection */
		{ 254, { "#PaintKit_so_orange_accents_Tag", "cz75_nitro" } },

		/* Winter Offensive Weapon Case */
		{ 255, { "#PaintKit_cu_m4_asimov_tag", "m4a4_asiimov" } },
		{ 256, { "#PaintKit_cu_sawedoff_octopump_tag", "sawedoff_the_kraken" } },
		{ 257, { "#PaintKit_cu_m4a1-s_elegant_Tag", "m4a1_guardian" } },
		{ 258, { "#PaintKit_cu_p250_refined_Tag", "p250_mehndi" } },
		{ 259, { "#PaintKit_cu_awp_cobra_tag", "awp_redline" } },
		{ 260, { "#PaintKit_cu_famas_pulse_tag", "famas_pulse" } },
		{ 261, { "#PaintKit_hy_marina_sunrise_tag", "elite_marina" } },
		{ 262, { "#PaintKit_am_thorny_rose_mp9_tag", "mp9_rose_iron" } },
		{ 263, { "#PaintKit_cu_skull_nova_tag", "nova_rising_skull" } },
		{ 264, { "#PaintKit_cu_sandstorm_tag", "galil_sandstorm" } },
		{ 265, { "#PaintKit_hy_kami_tag", "fiveseven_kami" } },
		{ 266, { "#PaintKit_aq_obsidian_tag", "m249_magma" } },
		{ 267, { "#PaintKit_am_turqoise_halftone_tag", "bizon_cobalt_halftone" } },

		/* The Arms Deal 3 Collection */
		{ 268, { "#PaintKit_am_diamond_plate_Tag", "cz75_thread_plate" } },
		{ 269, { "#PaintKit_am_fuschia_Tag", "cz75_the_fuschia_is_now" } },
		{ 270, { "#PaintKit_aq_etched_cz75_Tag", "cz75_victoria" } },
		{ 271, { "#PaintKit_am_p250_beaded_paint_Tag", "p250_undertow" } },
		{ 272, { "#PaintKit_am_fluted_tec9_Tag", "tec9_titanium_bit" } },
		{ 273, { "#PaintKit_aq_engraved_deagle_Tag", "deagle_heirloom" } },
		{ 274, { "#PaintKit_am_copper_flecks_Tag", "fiveseven_copper_galaxy" } },
		{ 275, { "#PaintKit_hy_poly_camo_Tag", "p2000_red_fragcam" } },
		{ 276, { "#PaintKit_so_panther_Tag", "elite_panther" } },
		{ 277, { "#PaintKit_aq_usp_stainless_Tag", "usp_stainless" } },
		{ 278, { "#PaintKit_hy_craquelure_Tag", "glock18_blue_fissure" } },

		/* Opreation Phoenix Case */
		{ 279, { "#PaintKit_cu_m4_asimov_tag", "awp_asiimov" } },
		{ 280, { "#PaintKit_cu_aug_chameleonaire_tag", "aug_chameleon" } },
		{ 281, { "#PaintKit_cu_ump_corporal_tag", "ump45_corporal" } },
		{ 282, { "#PaintKit_cu_awp_cobra_tag", "ak47_redline" } },
		{ 283, { "#PaintKit_cu_p90_trigon_tag", "p90_trigon" } },
		{ 284, { "#PaintKit_cu_mac10_redhot_tag", "mac10_heat" } },
		{ 285, { "#PaintKit_sp_negev_turq_terrain_tag", "negev_terrain" } },
		{ 286, { "#PaintKit_cu_nova_antique_tag", "nova_antique" } },

		/* Winter Offensive Weapon Case */
		{ 287, { "#PaintKit_cu_famas_pulse_tag", "famas_pulse" } },

		/* Operation Phoenix Weapon Case */
		{ 288, { "#PaintKit_an_famas_sgt_tag", "famas_sergeant" } },
		{ 289, { "#PaintKit_cu_sandstorm_tag", "tec9_sandstorm" } },
		{ 290, { "#PaintKit_cu_m4a1-s_elegant_Tag", "usp_guardian" } },
		{ 291, { "#PaintKit_cu_mag7_heaven_tag", "mag7_heaven_guard" } },

		/* The Bank Collection */
		{ 293, { "#PaintKit_hy_nerodia_Tag", "glock18_death_rattle" } },
		{ 294, { "#PaintKit_so_green_Tag", "g3sg1_green_apple" } },
		{ 295, { "#PaintKit_cu_money_Tag", "p250_frankline" } },
		{ 296, { "#PaintKit_am_crystallized_dark_Tag", "deagle_meteorite" } },
		{ 297, { "#PaintKit_so_orca_Tag", "galil_cz75_tuxedo" } },
		{ 298, { "#PaintKit_am_army_shine_Tag", "ssg553_negev_army_shine" } },
		{ 299, { "#PaintKit_am_oval_hex_Tag", "nova_caged_strip" } },
		{ 300, { "#PaintKit_cu_pinstripe_ak47_Tag", "ak47_emerald_pinstripe" } },

		/* Huntsman Collection */
		{ 301, { "#PaintKit_am_alloy_orange_Tag", "m4a1_atomic_alloy" } },
		{ 302, { "#PaintKit_cu_rubber_ak47_Tag", "ak47_vulcan" } },
		{ 303, { "#PaintKit_cu_tec_isaac_tag", "tec9_isaac" } },
		{ 304, { "#PaintKit_cu_immortal_ssg08_Tag", "ssg08_slashed" } },
		{ 305, { "#PaintKit_cu_progressiv_aug_Tag", "aug_torque" } },
		{ 306, { "#PaintKit_cu_nova_antique_tag", "bizon_antique" } },
		{ 307, { "#PaintKit_cu_retribution_beretta_Tag", "beretta_retribution" } },
		{ 308, { "#PaintKit_hy_kami_tag", "galil_kami" } },
		{ 309, { "#PaintKit_cu_howling_tag", "m4a4_howl" } },
		{ 310, { "#PaintKit_cu_decay_mac10_tag", "mac10_curse" } },
		{ 311, { "#PaintKit_cu_scorpius_p90_tag", "p90_desert_warfare" } },
		{ 312, { "#PaintKit_cu_cyrex_tag", "scar20_cyrex" } },
		{ 313, { "#PaintKit_cu_spitfire_tag", "usp_orion" } },
		{ 314, { "#PaintKit_cu_mag7_heaven_tag", "xm1014_heaven_guard" } },
		{ 315, { "#PaintKit_am_nitrogen_tag", "cz75_poison_dart" } },

		/* eSports 2014 Summer Case */
		{ 316, { "#PaintKit_cu_panther_ak47_Tag", "ak47_jaguar" } },
		{ 317, { "#PaintKit_cu_bratatat_negev_Tag", "negev_bratatat" } },

		/* The Overpass Collection */
		{ 318, { "#PaintKit_cu_usp_sandpapered_Tag", "usp_road_rash" } },
		{ 319, { "#PaintKit_hy_ssg08_marker_Tag", "ssg08_detour" } },

		/* eSports 2014 Summer Case */
		{ 320, { "#PaintKit_hy_snakeskin_red_Tag", "xm1014_red_python" } },

		/* The Overpass Collection */
		{ 321, { "#PaintKit_cu_m4a1-s_silence_Tag", "m4a1_master_piece" } },

		/* The Safehous Collection */
		{ 322, { "#PaintKit_so_orange_accents_Tag", "m4a1_nitro" } },

		/* Cobblestone Collection */
		{ 323, { "#PaintKit_aq_steel_bravo_Tag", "sawedoff_rust_coat" } },
		{ 325, { "#PaintKit_am_royal_Tag", "cz75_chalice" } },
		{ 326, { "#PaintKit_am_metals_Tag", "m4a1_knights" } },
		{ 327, { "#PaintKit_am_chainmail_Tag", "p2000_chainmail" } },
		{ 328, { "#PaintKit_aq_handcannon_Tag", "deagle_hand_cannon" } },
		{ 329, { "#PaintKit_am_metal_inlay_Tag", "mp9_dark_age" } },
		{ 330, { "#PaintKit_hy_vines_Tag", "elite_briar" } },
		{ 332, { "#PaintKit_so_indigo_Tag", "usp_royal_blue" } },
		{ 333, { "#PaintKit_so_indigo_and_grey_Tag", "mac10_indigo" } },

		/* Huntsman Collection */
		{ 334, { "#PaintKit_am_gyrate_tag", "cz75_twist" } },
		{ 335, { "#PaintKit_an_royalbleed_tag", "p90_module" } },
		{ 336, { "#PaintKit_cu_titanstorm_tag", "m4a4_desert_strike" } },
		{ 337, { "#PaintKit_cu_korupt_tag", "mac10_tatter" } },
		{ 338, { "#PaintKit_cu_famas_pulse_tag", "p2000_pulse" } },
		{ 339, { "#PaintKit_cu_kaiman_tag", "usp_kaiman" } },

		/* The Bagage Collection */
		{ 340, { "#PaintKit_cu_well_traveled_ak47_Tag", "ak47_jet_set" } },
		{ 341, { "#PaintKit_cu_green_leather_Tag", "ak47_first_class" } },
		{ 342, { "#PaintKit_cu_brown_leather_p90_Tag", "p90_leather" } },
		{ 343, { "#PaintKit_cu_luggage_mac10_Tag", "mac10_commuter" } },

		/* The Cobblestone Collection */
		{ 344, { "#PaintKit_cu_medieval_dragon_awp_Tag", "awp_dragon_lore" } },

		/* The Bagage Collection */
		{ 345, { "#PaintKit_cu_green_leather_Tag", "sawedoff_first_class" } },
		{ 346, { "#PaintKit_cu_luggage_p2000_Tag", "p2000_coach_class" } },
		{ 347, { "#PaintKit_aq_pilot_deagle_Tag", "deagle_pilot" } },
		{ 348, { "#PaintKit_cu_leather_xm1014_Tag", "xm1014_red_leather" } },

		/* Breackout Weapon Case */
		{ 349, { "#PaintKit_cu_bizon-osiris_tag", "bizon_osiris" } },
		{ 350, { "#PaintKit_cu_c75a-tiger_tag", "cz75_tigris" } },
		{ 351, { "#PaintKit_cu_deagle_aureus_tag", "deagle_conspiracy" } },
		{ 352, { "#PaintKit_aq_57_feathers_tag", "fiveseven_fowl_play" } },
		{ 353, { "#PaintKit_cu_glock-liquescent_tag", "glock18_water_elemental" } },
		{ 354, { "#PaintKit_cu_mp7-commander_tag", "mp7_urban_hazard" } },
		{ 355, { "#PaintKit_cu_titanstorm_tag", "negev_desert_strike" } },
		{ 356, { "#PaintKit_cu_nova_koi_tag", "nova_koi" } },
		{ 357, { "#PaintKit_cu_p2000_ivory_tag", "p2000_ivory" } },
		{ 358, { "#PaintKit_cu_bittersweet_tag", "p250_supernova" } },
		{ 359, { "#PaintKit_cu_m4_asimov_tag", "p90_asimov" } },
		{ 360, { "#PaintKit_cu_cyrex_tag", "m4a1_cyrex" } },
		{ 361, { "#PaintKit_aq_leviathan_tag", "ssg08_abbys" } },
		{ 362, { "#PaintKit_hy_lines_orange_tag", "ump45_labyrinth" } },
		{ 363, { "#PaintKit_cu_luggage_sg553_Tag", "sg553_traveler" } },
		{ 364, { "#PaintKit_cu_luggage_usp-s_Tag", "usp_business_class" } },
		{ 365, { "#PaintKit_hy_plaid1_Tag", "mp7_olive_plaid" } },
		{ 366, { "#PaintKit_chy_plaid2_Tag", "mp9_green_plaid" } },

		/* Cache Collection */
		{ 367, { "#PaintKit_am_nuclear_pattern1_glock_Tag", "glock18_reactor" } },
		{ 368, { "#PaintKit_hy_nuclear_pattern2_mp9_Tag", "mp9_setting_sun" } },
		{ 369, { "#PaintKit_sp_nuclear_pattern3_negev_Tag", "negev_nuclear_waste" } },
		{ 370, { "#PaintKit_am_nuclear_skulls1_xm1014_Tag", "xm1014_bone_machine" } },
		{ 371, { "#PaintKit_am_nuclear_skulls2_famas_Tag", "famas_styx" } },
		{ 372, { "#PaintKit_am_nuclear_skulls3_mac10_Tag", "mac10_nuclear_garden" } },
		{ 373, { "#PaintKit_hy_nuclear_skulls4_p250_Tag", "p250_contamination" } },
		{ 374, { "#PaintKit_hy_nuclear_skulls5_tec9_Tag", "tec9_toxic" } },
		{ 375, { "#PaintKit_sp_nukestripe_orange_Tag", "aug_radiation_hazard" } },
		{ 376, { "#PaintKit_so_grey_nuclear_green_bizon_Tag", "bizon_chemical_green" } },
		{ 377, { "#PaintKit_so_grey_nuclear_orange_five_seven_Tag", "fiveseven_hot_shot" } },
		{ 378, { "#PaintKit_sp_nukestripe_maroon_Tag", "sg553_fallout_warning" } },
		{ 379, { "#PaintKit_cu_cerbrus_galil_Tag", "galil_cerberus" } },

		/* Vanguard Case */
		{ 380, { "#PaintKit_cu_tribute_ak47_Tag", "ak47_wasteland_rebel" } },
		{ 381, { "#PaintKit_aq_glock_coiled_Tag", "glock18_grinder" } },
		{ 382, { "#PaintKit_am_g3sg1_murky_Tag", "g3sg1_murky" } },
		{ 383, { "#PaintKit_aq_m4a1s_basilisk_Tag", "m4a1s_basilisk" } },
		{ 384, { "#PaintKit_cu_m4a4_griffin_Tag", "m4a4_griffin" } },
		{ 385, { "#PaintKit_sp_mag7_firebitten_Tag", "mag7_firestarter" } },
		{ 386, { "#PaintKit_cu_mp9_chevron_Tag", "mp9_dart" } },

		/* Breackout Weapon Case */
		{ 387, { "#PaintKit_cu_mp7-commander_tag", "mp7_urban_hazard" } },

		/* Vanguard Case */
		{ 388, { "#PaintKit_aq_p250_cartel_Tag", "p250_cartel" } },
		{ 389, { "#PaintKit_cu_p2000_fire_elemental_Tag", "p2000_fire_elemental" } },
		{ 390, { "#PaintKit_aq_sawedoff_blackgold_Tag", "sawedoff_highwayman" } },
		{ 391, { "#PaintKit_cu_scar20_intervention_Tag", "scar20_cardiac" } },
		{ 392, { "#PaintKit_sp_ump45_d-visions_Tag", "ump45_delusion" } },
		{ 393, { "#PaintKit_cu_xm1014_caritas_Tag", "xm1014_tranquility" } },
		{ 394, { "#PaintKit_aq_p250_cartel_Tag", "p250_cartel" } },

		/* Chroma Case */
		{ 395, { "#PaintKit_am_awp_glory_Tag", "awp_man-o-war" } },
		{ 396, { "#PaintKit_cu_elites_urbanstorm_Tag", "elites_urban_shock" } },
		{ 397, { "#PaintKit_aq_deagle_naga_Tag", "deagle_naga" } },
		{ 398, { "#PaintKit_cu_galil_abrasion_Tag", "galil_chatterbox" } },
		{ 399, { "#PaintKit_cu_glock_deathtoll_Tag", "glock18_catacombs" } },
		{ 400, { "#PaintKit_cu_m4a4_ancestral_Tag", "m4a4_dragon_king" } },
		{ 401, { "#PaintKit_cu_m249_sektor_Tag", "m249_system_lock" } },
		{ 402, { "#PaintKit_am_mac10_malachite_Tag", "mac10_malachite" } },
		{ 403, { "#PaintKit_cu_mp9_deadly_poison_Tag", "mp9_deadly_poison" } },
		{ 404, { "#PaintKit_cu_p250_mandala_Tag", "p250_muertos" } },
		{ 405, { "#PaintKit_cu_sawedoff_deva_Tag", "sawedoff_serinity" } },
		{ 406, { "#PaintKit_aq_scar20_leak_Tag", "scar20_grotto" } },
		{ 407, { "#PaintKit_aq_xm1014_sigla_Tag", "xm1014_quicksilver" } },

		/* Knifes */
		{ 409, { "#PaintKit_an_tiger_orange_Tag", "tiger" } },
		{ 410, { "#PaintKit_aq_damascus_Tag", "damascus" } },
		{ 411, { "#PaintKit_aq_damascus_Tag", "damascus_90" } },
		{ 413, { "#PaintKit_am_marble_fade_Tag", "marble_fade" } },
		{ 414, { "#PaintKit_aq_steel_bravo_Tag", "steel_knife" } },
		{ 415, { "#PaintKit_am_marbleized_Tag", "ruby_marbleized" } },
		{ 416, { "#PaintKit_am_marbleized_Tag", "sapphire_marbleized" } },
		{ 417, { "#PaintKit_am_marbleized_Tag", "blackpearl_marbleized" } },
		{ 418, { "#PaintKit_am_marbleized_Tag", "doppler_phase1" } },
		{ 419, { "#PaintKit_am_marbleized_Tag", "doppler_phase2" } },
		{ 420, { "#PaintKit_am_marbleized_Tag", "doppler_phase3" } },
		{ 421, { "#PaintKit_am_marbleized_Tag", "doppler_phase4" } },

		/* Chroma 2 Case */
		{ 422, { "#PaintKit_cu_ak47_mastery_Tag", "ak47_elite_build" } },
		{ 423, { "#PaintKit_aq_mp7_ultramodern_Tag", "mp7_armor_core" } },
		{ 424, { "#PaintKit_aq_awp_twine_Tag", "awp_worm_god" } },
		{ 425, { "#PaintKit_am_bronze_sparkle_Tag", "deagle_bronze_deco" } },
		{ 426, { "#PaintKit_aq_p250_contour_Tag", "p250_valence" } },
		{ 427, { "#PaintKit_cu_fiveseven_banana_Tag", "fiveseven_monkey_business" } },
		{ 428, { "#PaintKit_cu_galil_eco_Tag", "galil_eco" } },
		{ 429, { "#PaintKit_aq_famas_jinn_Tag", "famas_djinn" } },
		{ 430, { "#PaintKit_cu_m4a1_hyper_beast_Tag", "m4a1_hyper_beast" } },

		/* Operation Phoenix Weapon Case */
		{ 431, { "#PaintKit_cu_mac10_redhot_tag", "mac10_heat" } },

		/* Chroma 2 Case */
		{ 432, { "#PaintKit_am_awp_glory_Tag", "negev_man-o-war" } },
		{ 433, { "#PaintKit_cu_mac10_neonrider_Tag", "mac10_neonrider" } },
		{ 434, { "#PaintKit_cu_sawedoff_origami_Tag", "sawedoff_origami" } },
		{ 435, { "#PaintKit_cu_cz75_precision_Tag", "cz75_pole_position" } },
		{ 436, { "#PaintKit_am_ump_racer_Tag", "ump45_grand_prix" } },

		/* The Chop Shop Collection */
		{ 437, { "#PaintKit_am_aqua_flecks_Tag", "glock18_twilight_galaxy" } },

		/* The God's and Monsters Collection */
		{ 438, { "#PaintKit_cu_chronos_g3sg1_Tag", "g3sg1_chronos" } },
		{ 439, { "#PaintKit_hy_hades_Tag", "tec9_hades" } },
		{ 440, { "#PaintKit_hy_icarus_Tag", "m4a1_icarus_fell" } },
		{ 441, { "#PaintKit_cu_labyrinth_Tag", "ump45_minotaurs_labyrinth" } },
		{ 442, { "#PaintKit_sp_labyrinth1_Tag", "mp7_asterion" } },
		{ 443, { "#PaintKit_sp_labyrinth2_Tag", "p2000_pathfinder" } },
		{ 444, { "#PaintKit_sp_labyrinth3_Tag", "aug_daedalus" } },

		/* The Chop Shop Collection */
		{ 445, { "#PaintKit_an_red_Tag", "m4a1_hot_rod" } },

		/* The God's and Monsters Collection */
		{ 446, { "#PaintKit_cu_medusa_awp_Tag", "awp_medusa" } },

		/* The Chop Shop Collection */
		{ 447, { "#PaintKit_gs_mother_of_pearl_elite_Tag", "elite_duelist" } },

		/* The God's and Monsters Collection */
		{ 448, { "#PaintKit_aa_pandora_Tag", "mp9_pandoras_box" } },
		{ 449, { "#PaintKit_cu_poseidon_Tag", "m4a4_poseidon" } },
		{ 450, { "#PaintKit_hy_zodiac1_Tag", "m249_shipping_forecast" } },
		{ 451, { "#PaintKit_hy_zodiac2_Tag", "awp_sun_in_leo" } },
		{ 452, { "#PaintKit_hy_zodiac3_Tag", "elite_nova_moon_in_libra" } },

		/* The Chop Shop Collection */
		{ 453, { "#PaintKit_an_emerald_bravo_Tag", "cz75_emerald" } },
		{ 454, { "#PaintKit_so_khaki_green_Tag", "usp_para_green" } },

		/* Rising Sun Collection */
		{ 455, { "#PaintKit_cu_anime_aug_Tag", "aug_akihobara" } },
		{ 456, { "#PaintKit_am_bamboo_jungle_Tag", "ak47_hydroponic" } },
		{ 457, { "#PaintKit_hy_bamboo_jungle_ink_Tag", "bizon_bamboo_print" } },
		{ 458, { "#PaintKit_hy_bamboo_jungle_black_Tag", "sawedoff_bamboo_shadow" } },
		{ 459, { "#PaintKit_hy_bamboo_jungle_Tag", "tec9_bamboo_forest" } },
		{ 460, { "#PaintKit_am_geometric_steps_Tag", "galil_aqua_terrace" } },
		{ 462, { "#PaintKit_hy_geometric_steps_green_Tag", "mag7_counter_terrace" } },
		{ 463, { "#PaintKit_hy_geometric_steps_yellow_Tag", "tec9_terrace" } },
		{ 464, { "#PaintKit_hy_kimono_diamonds_Tag", "fiveseven_neon_kimono" } },
		{ 465, { "#PaintKit_hy_kimono_diamonds_orange_Tag", "g3sg1_orange_kimono" } },
		{ 466, { "#PaintKit_hy_kimono_diamonds_red_Tag", "specialist_crimson_kimono" } },
		{ 467, { "#PaintKit_sp_kimono_diamonds_Tag", "fiveseven_neon_kimono" } },
		{ 468, { "#PaintKit_am_seastorm_Tag", "deagle_midnight_storm" } },
		{ 469, { "#PaintKit_am_seastorm_blood_Tag", "deagle_sunset_storm_ichi" } },
		{ 470, { "#PaintKit_am_seastorm_shojo_Tag", "deagle_sunset_storm_vol.2" } },
		{ 471, { "#PaintKit_am_kimono_sunrise_Tag", "m4a4_daybreak" } },

		/* The Chop Shop Collection */
		{ 472, { "#PaintKit_am_so_keycolors_Tag", "m249_impact_drill" } },
		{ 473, { "#PaintKit_so_aqua_Tag", "mag7_seabird" } },

		/* Falcion Case */
		{ 474, { "#PaintKit_cu_ak47_courage_alt_Tag", "ak47_aquamarine_revenge" } },
		{ 475, { "#PaintKit_cu_m4a1_hyper_beast_Tag", "awp_hyper_beast" } },
		{ 476, { "#PaintKit_cu_cz75a_chastizer_Tag", "cz75a_chastizer" } },
		{ 477, { "#PaintKit_am_famas_dots_Tag", "famas_dots" } },
		{ 478, { "#PaintKit_cu_galilar_particles_Tag", "galilar_particles" } },
		{ 479, { "#PaintKit_aq_glock18_flames_blue_Tag", "glock18_bunsen_burner" } },
		{ 480, { "#PaintKit_cu_m4a4_evil_daimyo_Tag", "m4a4_evil_daimyo" } },
		{ 481, { "#PaintKit_cu_mp7_nemsis_Tag", "mp7_nemesis" } },
		{ 482, { "#PaintKit_am_mp9_nitrogen_Tag", "mp9_ruby_poison_dart" } },
		{ 483, { "#PaintKit_cu_negev_annihilator_Tag", "negev_loudmouth" } },
		{ 484, { "#PaintKit_cu_nova_ranger_Tag", "nova_ranger" } },
		{ 485, { "#PaintKit_aq_p2000_boom_Tag", "p2000_handgun" } },
		{ 486, { "#PaintKit_cu_ak47_mastery_Tag", "ak47_elite_build" } },
		{ 487, { "#PaintKit_cu_cyrex_tag", "sg553_cyrex" } },
		{ 488, { "#PaintKit_cu_ump45_uproar_Tag", "ump45_riot" } },
		{ 489, { "#PaintKit_cu_usp_progressiv_Tag", "usp_torque" } },

		/* Shadow Case */
		{ 490, { "#PaintKit_cu_ak47_winter_sport_Tag", "ak47_frontside_misty" } },
		{ 491, { "#PaintKit_cu_dualberretta_dragons_Tag", "elite_dualing_dragons" } },
		{ 492, { "#PaintKit_cu_famas_lenta_Tag", "famas_survivor_z" } },
		{ 493, { "#PaintKit_gs_g3sg1_flux_purple_Tag", "g3sg1_flux" } },
		{ 494, { "#PaintKit_gs_galil_nightwing_Tag", "galil_stone_cold" } },
		{ 495, { "#PaintKit_gs_glock18_wrathys_Tag", "glock18_wraiths" } },
		{ 496, { "#PaintKit_gs_m249_nebula_crusader_Tag", "m249_nebula_crusader" } },
		{ 497, { "#PaintKit_gs_m4a1s_snakebite_gold_Tag", "m4a1_golden_coil" } },
		{ 498, { "#PaintKit_cu_mac10_alekhya_duo_Tag", "mac10_rangeen" } },
		{ 499, { "#PaintKit_cu_mag7_myrcene_Tag", "mag7_cobalt_core" } },
		{ 500, { "#PaintKit_cu_mp7_classified_Tag", "mp7_special_delivery" } },
		{ 501, { "#PaintKit_hy_p250_crackshot_Tag", "p250_wingshot" } },
		{ 502, { "#PaintKit_gs_scar20_peacemaker03_Tag", "scar20_green_marine" } },
		{ 503, { "#PaintKit_cu_ssg08_technicality_Tag", "ssg08_big_iron" } },
		{ 504, { "#PaintKit_cu_usp_kill_confirmed_Tag", "usp_kill_confirmed" } },
		{ 505, { "#PaintKit_aq_xm1014_scumbria_Tag", "xm1014_scumbria" } },

		/* Revolver Case */
		{ 506, { "#PaintKit_cu_ak47_point_disarray_Tag", "ak47_point_disarray" } },
		{ 507, { "#PaintKit_am_aug_jumble_Tag", "aug_ricochet" } },
		{ 508, { "#PaintKit_cu_bizon_noxious_Tag", "bizon_fuel_rod" } },
		{ 509, { "#PaintKit_aq_deagle_corinthian_Tag", "deagle_corinthian" } },
		{ 510, { "#PaintKit_cu_fiveseven_retrobution_Tag", "fiveseven_retrobution" } },
		{ 511, { "#PaintKit_cu_g3sg1_executioner_Tag", "g3sg1_executioner" } },
		{ 512, { "#PaintKit_gs_m4a4_royal_squire_Tag", "m4a4_royal_paladin" } },
		{ 514, { "#PaintKit_cu_negev_impact_Tag", "negev_power_loader" } },
		{ 515, { "#PaintKit_am_p2000_imperial_red_Tag", "p2000_imperial" } },
		{ 516, { "#PaintKit_cu_p90_shapewood_Tag", "p90_shapewood" } },
		{ 517, { "#PaintKit_gs_sawedoff_necromancer_Tag", "sawedoff_yorick" } },
		{ 518, { "#PaintKit_hy_scar20_jungler_Tag", "scar20_outbreak" } },
		{ 519, { "#PaintKit_gs_sg553_tiger_moth_Tag", "sg553_tiger_moth" } },
		{ 520, { "#PaintKit_cu_tec9_avalanche_Tag", "tec9_avalanche" } },
		{ 521, { "#PaintKit_aq_xm1014_hot_rod_Tag", "xm1014_teclu_burner" } },

		/* Revolver Case */
		{ 522, { "#PaintKit_aa_fade_Tag", "r8_fade" } },
		{ 523, { "#PaintKit_aa_fade_metallic_Tag", "(r8)_fade_metallic" } },

		/* Wildfire Case */
		{ 524, { "#PaintKit_gs_ak47_supercharged_Tag", "ak47_fuel_injector" } },

		/* Chroma 2 Case */
		{ 525, { "#PaintKit_cu_ak47_mastery_Tag", "ak47_elite_build" } },

		/* Wildfire Case */
		{ 526, { "#PaintKit_cu_bizon_citizen_Tag", "bizon_photic_zone" } },
		{ 527, { "#PaintKit_aq_deserteagle_kumichodragon_Tag", "deagle_kumicho_dragon" } },

		/* Vanguard Case */
		{ 528, { "#PaintKit_aq_p250_cartel_Tag", "p250_cartel" } },

		/* Chroma 2 Case */
		{ 529, { "#PaintKit_aq_p250_contour_Tag", "p250_valence" } },

		/* Wildfire Case */
		{ 530, { "#PaintKit_cu_fiveseven_augmented_Tag", "fiveseven_triumvirat" } },
		{ 532, { "#PaintKit_gs_glock18_award_Tag", "glock18_royal_legion" } },
		{ 533, { "#PaintKit_gs_m4a4_pioneer_Tag", "m4a4_the_buttlestar" } },
		{ 534, { "#PaintKit_am_mac10_electricity_Tag", "mac10_lapis_gator" } },
		{ 535, { "#PaintKit_gs_mag7_praetorian_Tag", "mag7_praetorian" } },
		{ 536, { "#PaintKit_sp_mp7_impire_Tag", "mp7_impire" } },
		{ 537, { "#PaintKit_cu_m4a1_hyper_beast_Tag", "nova_hyper_beast" } },
		{ 538, { "#PaintKit_cu_ssg08_necropos_Tag", "ssg08_necropos" } },
		{ 539, { "#PaintKit_gs_tec9_jambiya_Tag", "tec9_jambiya" } },
		{ 540, { "#PaintKit_gs_usp_voltage_Tag", "usp_lead_conduit" } },

		/* Chroma 3 Case */
		{ 541, { "#PaintKit_cu_aug_swallows_Tag", "aug_fleet_flock" } },
		{ 542, { "#PaintKit_cu_bizon_Curse_Tag", "bizon_judgement_of_anubis" } },
		{ 543, { "#PaintKit_gs_cz75a_redastor_Tag", "cz75a_red_astor" } },
		{ 544, { "#PaintKit_gs_dualberettas_ventilators_Tag", "elite_ventilators" } },
		{ 545, { "#PaintKit_sp_g3sg1_militiaorange_Tag", "g3sg1_orange_crush" } },
		{ 546, { "#PaintKit_gs_galilar_incenerator_Tag", "galil_firefight" } },
		{ 547, { "#PaintKit_cu_m249_spectre_Tag", "m249_spectre" } },
		{ 548, { "#PaintKit_cu_m4a1s_soultaker_Tag", "m4a1_chanticos_fire" } },
		{ 549, { "#PaintKit_am_mp9_bioleak_Tag", "mp9_bioleak" } },
		{ 550, { "#PaintKit_hy_p2000_oceani_Tag", "p2000_oceanic" } },
		{ 551, { "#PaintKit_cu_p250_asiimov_Tag", "p250_asiimov" } },
		{ 552, { "#PaintKit_gs_sawedoff_fubar_Tag", "sawedoff_fubar" } },
		{ 553, { "#PaintKit_cu_sg553_atlas_Tag", "sg553_atlas" } },
		{ 554, { "#PaintKit_gs_ssg08_armacore_Tag", "ssg08_ghost_crusader" } },
		{ 555, { "#PaintKit_am_tec9_redblast_Tag", "tec9_re-entry" } },
		{ 556, { "#PaintKit_cu_ump45_primalsaber_Tag", "ump45_primal_saber" } },
		{ 557, { "#PaintKit_cu_xm1014_spectrum_Tag", "xm1014_black_tie" } },


		{ 558, { "#Paintkit_cu_lore_Tag", "bayonet_lore" } },
		{ 559, { "#Paintkit_cu_lore_Tag", "flip_lore" } },
		{ 560, { "#Paintkit_cu_lore_Tag", "gut_lore" } },
		{ 561, { "#Paintkit_cu_lore_Tag", "karam_lore" } },
		{ 562, { "#Paintkit_cu_lore_Tag", "m9_bay_lore" } },
		{ 563, { "#Paintkit_cu_stonewash_Tag", "bayonet_stonewash" } },
		{ 564, { "#Paintkit_cu_stonewash_Tag", "flip_stonewash" } },
		{ 565, { "#Paintkit_cu_stonewash_Tag", "gut_stonewash" } },
		{ 566, { "#Paintkit_cu_stonewash_Tag", "karam_stonewash" } },
		{ 567, { "#Paintkit_cu_stonewash_Tag", "m9_bay_stonewash" } },
		{ 568, { "#PaintKit_am_marbleized_g_Tag", "emerald_marbleized" } },
		{ 569, { "#PaintKit_am_marbleized_g_Tag", "gamma_doppler_phase1" } },
		{ 570, { "#PaintKit_am_marbleized_g_Tag", "gamma_doppler_phase2" } },
		{ 571, { "#PaintKit_am_marbleized_g_Tag", "gamma_doppler_phase3" } },
		{ 572, { "#PaintKit_am_marbleized_g_Tag", "gamma_doppler_phase4" } },
		{ 573, { "#PaintKit_gs_autotronic_Tag", "bayonet_autotronic" } },
		{ 574, { "#PaintKit_gs_autotronic_Tag", "flip_autotronic" } },
		{ 575, { "#PaintKit_gs_autotronic_Tag", "gut_autotronic" } },
		{ 576, { "#PaintKit_gs_autotronic_Tag", "karam_autotronic" } },
		{ 577, { "#PaintKit_gs_autotronic_Tag", "m9_bay_autotronic" } },
		{ 578, { "#PaintKit_hy_ocean_Tag", "ocean_knife" } },
		{ 579, { "#PaintKit_hy_ocean_Tag", "ocean_knife_90" } },
		{ 580, { "#PaintKit_am_marked_up_Tag", "marked_up" } },
		{ 581, { "#PaintKit_am_marked_up_Tag", "marked_up_90" } },
		{ 582, { "#PaintKit_am_marked_up_Tag", "marked_up_fine" } },

		/* Gamma Case */
		{ 583, { "#PaintKit_gs_aug_aristocrat_Tag", "aug_aristocrat" } },
		{ 584, { "#PaintKit_gs_awp_phobos_Tag", "awp_phobos" } },
		{ 585, { "#PaintKit_cu_five_seven_daimyo_Tag", "five_seven_daimyo" } },
		{ 586, { "#PaintKit_cu_glock_wasteland_rebel_Tag", "glock18_wasteland_rebel" } },
		{ 587, { "#PaintKit_gs_m4a1_mecha_industries_Tag", "m4a1_mecha_industries" } },
		{ 588, { "#PaintKit_cu_m4a4_desolate_space_Tag", "m4a4_desolate_space" } },
		{ 589, { "#PaintKit_aq_mac_10_alien_camo_Tag", "mac_10_carnivore" } },
		{ 590, { "#PaintKit_aq_nova_sci_fi_Tag", "nova_exo" } },
		{ 591, { "#PaintKit_gs_p2000_imperial_dragon_Tag", "p2000_imperial_dragon" } },
		{ 592, { "#PaintKit_gs_p250_metal_panels_Tag", "p250_iron_clad" } },
		{ 593, { "#PaintKit_gs_p90_full_throttle_Tag", "p90_chopper" } },
		{ 594, { "#PaintKit_gs_pp_bizon_harvester_Tag", "bizon_harvester" } },
		{ 595, { "#PaintKit_cu_r8_cybersport_Tag", "r8_reboot" } },
		{ 596, { "#PaintKit_cu_sawed_off_lime_Tag", "sawedoff_limelight" } },
		{ 597, { "#PaintKit_gs_scar20_bloodsport_Tag", "scar20_bloodsport" } },
		{ 598, { "#PaintKit_cu_sg553_aerial_Tag", "sg553_aerial" } },
		{ 599, { "#PaintKit_am_tec_9_sea_salt_Tag", "tec_9_ice_cap" } },

		/* Gamma 2 Case */
		{ 600, { "#PaintKit_cu_AK47_Anarchy_Tag", "ak47_neon_revolution" } },
		{ 601, { "#PaintKit_gs_AUG_Syd_Mead_Tag", "aug_syd_mead" } },
		{ 602, { "#PaintKit_gs_CZ75_Tread_Tag", "cz75_imprint" } },
		{ 603, { "#PaintKit_aq_Desert_Eagle_Constable_Tag", "deagle_directive" } },
		{ 604, { "#PaintKit_gs_FAMAS_Rally_Tag", "famas_roll_cage" } },
		{ 605, { "#PaintKit_aq_Five_Seven_Scumbria_Tag", "fiveseven_scumbria" } },
		{ 606, { "#PaintKit_gs_G3SG1_Ventilator_Tag", "g3sg1_ventilator" } },
		{ 607, { "#PaintKit_cu_Glock18_Weasel_Tag", "glock18_weasel" } },
		{ 608, { "#PaintKit_cu_MAG7_Tribal_Tag", "mag7_petroglyph" } },
		{ 609, { "#PaintKit_cu_MP9_Narcis_Tag", "mp9_airlock" } },
		{ 610, { "#PaintKit_hy_Negev_Dazzle_Tag", "negev_dazzle" } },
		{ 611, { "#PaintKit_cu_P90_Grimm_Tag", "p90_grim" } },
		{ 612, { "#PaintKit_gs_SCAR20_Powercore_Tag", "scar20_powercore" } },
		{ 613, { "#PaintKit_cu_SG556_Triarch_Tag", "sg553_triarch" } },
		{ 614, { "#PaintKit_gs_TEC9_Supercharged_Tag", "tec9_fuel_injector" } },
		{ 615, { "#PaintKit_cu_UMP45_Metritera_Tag", "ump45_briefing" } },
		{ 616, { "#PaintKit_hy_XM1014_Fractal_Blue_Tag", "xm1014_slipstream" } },

		/* Gloves Case */
		{ 622, { "#PaintKit_am_czv2_mf_Tag", "cz75_polymer" } },
		{ 623, { "#PaintKit_aq_glock_dark-fall_Tag", "glock_ironwork" } },
		{ 624, { "#PaintKit_cu_ssg08_dragonfire_scope_Tag", "ssg08_dragonfire" } },
		{ 625, { "#PaintKit_gs_dual_berettas_golden_venice_Tag", "elite_royal_consorts" } },
		{ 626, { "#PaintKit_gs_famas_mecha_Tag", "famas_mecha_industries" } },
		{ 627, { "#PaintKit_gs_final_pooldeadv2_Tag", "mp7_cirrus" } },
		{ 628, { "#PaintKit_gs_g3sg1_viper_yellow_Tag", "g3sg1_stinger" } },
		{ 629, { "#PaintKit_cu_galil_ar-camo_Tag", "galil_black_sand" } },
		{ 630, { "#PaintKit_aa_hide-mp9_Tag", "mp9_sand_scale" } },
		{ 631, { "#PaintKit_cu_m4a1_flashback_Tag", "m4a1_flashback" } },
		{ 632, { "#PaintKit_gs_m4a4_sector_Tag", "m4a4_buzz_kill" } },
		{ 633, { "#PaintKit_am_mag7_malform_Tag", "mag7_sonar" } },
		{ 634, { "#PaintKit_am_nova_sand_Tag", "nova_gila" } },
		{ 635, { "#PaintKit_gs_p2000-sport_Tag", "p2000_turf" } },
		{ 636, { "#PaintKit_gs_p90_shallow_grave_Tag", "p90_shallow_grave" } },
		{ 637, { "#PaintKit_cu_usp_cyrex_Tag", "usp_cyrex" } },
		{ 638, { "#PaintKit_cu_wp_sawedoff_Tag", "sawedoff_wasteland_princess" } },

		/* Spectrum Case */
		{ 639, { "#PaintKit_gs_ak47_bloodsport_Tag", "ak47_bloodsport" } },
		{ 640, { "#PaintKit_cu_awp_psychopath_Tag", "awp_fever_dream" } },
		{ 641, { "#PaintKit_hy_bizon_torn_green_Tag", "bizon_jungle_slipstream" } },
		{ 642, { "#PaintKit_cu_blueprint_scar_Tag", "scar20_blueprint" } },
		{ 643, { "#PaintKit_gs_cz_snakes_purple_Tag", "cz75_xiangliu" } },
		{ 644, { "#PaintKit_gs_m4a1_decimator_Tag", "m4a1_decimator" } },
		{ 645, { "#PaintKit_cu_desert_eagle_corroden_Tag", "deagle_oxid_blaze" } },
		{ 646, { "#PaintKit_cu_fiveseven_vein_Tag", "fiveseven_capillary" } },
		{ 647, { "#PaintKit_sp_galil_wave_Tag", "galil_crimson_tsunami" } },
		{ 648, { "#PaintKit_sp_m249_frog_original_Tag", "m249_emerald_poison_dart" } },
		{ 649, { "#PaintKit_sp_mp7_tribal_yellow_Tag", "mp7_akoben" } },
		{ 650, { "#PaintKit_am_p250_sputnik_Tag", "p250_ripple" } },
		{ 651, { "#PaintKit_aa_mac10_the_last_dive_Tag", "mac10_last_dive" } },
		{ 652, { "#PaintKit_gs_ump_abyss_Tag", "ump45_scaffold" } },
		{ 653, { "#PaintKit_cu_usps_noir_Tag", "usp_neo-noir" } },
		{ 654, { "#PaintKit_aq_xm_leaf_fade_Tag", "xm1014_seasons" } },
		{ 655, { "#PaintKit_aq_sawedoff_zander2_Tag", "sawedoff_zander" } },

		/* Operation Hydra Case */
		{ 656, { "#PaintKit_gs_ak_colony01_red_tag", "ak47_orbit_mk01" } },
		{ 657, { "#PaintKit_cu_usps_blueprint_tag", "usp_blueprint" } },
		{ 658, { "#PaintKit_gs_dualberettas_cobra_Tag", "elite_cobra_strike" } },
		{ 659, { "#PaintKit_sp_famas_macabre_tag", "famas_macabre" } },
		{ 660, { "#PaintKit_cu_fiveseven_hyperbeast_Tag", "fiveseven_hyperbeast" } },
		{ 661, { "#PaintKit_cu_galil_candychaos_Tag", "galil_sugar_rush" } },
		{ 662, { "#PaintKit_cu_awp_hannya_Tag", "awp_oni_taiji" } },
		{ 663, { "#PaintKit_cu_m4a1s_metritera_Tag", "m4a1_briefing" } },
		{ 664, { "#PaintKit_cu_m4a4_hellfire_Tag", "m4a4_hellfire" } },
		{ 665, { "#PaintKit_am_mac10_aloha_Tag", "mac10_aloha" } },
		{ 666, { "#PaintKit_am_mag7_caustic_Tag", "mag7_hard_water" } },
		{ 667, { "#PaintKit_cu_p2000_hunter_Tag", "p2000_woodsman" } },
		{ 668, { "#PaintKit_cu_p250_axiom_Tag", "p250_red_rock" } },
		{ 669, { "#PaintKit_hy_p90_barebones_blue_Tag", "p90_death_grip" } },
		{ 670, { "#PaintKit_cu_ssg08_deathshead_Tag", "ssg08_deaths_head" } },
		{ 671, { "#PaintKit_aq_tec9_chalk_pattern_tag", "tec9_cut_out" } },
		{ 672, { "#PaintKit_aq_ump45_flameflower_Tag", "ump45_metal_flowers" } },

		/* Spectrum 2 Case */
		{ 673, { "#PaintKit_aq_sawed-off_flower_Tag", "sawedoff_morris" } },
		{ 674, { "#PaintKit_cu_aug_orange_triangle_Tag", "aug_triqua" } },
		{ 675, { "#PaintKit_gs_ak47_empress_Tag", "ak47_the_empress" } },
		{ 676, { "#PaintKit_cu_bizon_all_in_Tag", "bizon_high_rolling" } },
		{ 677, { "#PaintKit_gs_g3sg1_cetme_redux_Tag", "g3sg1_hunter" } },
		{ 678, { "#PaintKit_cu_p250_cybercroc_Tag", "p250_see_ya_later" } },
		{ 679, { "#PaintKit_cu_mp9_goo_Tag", "mp9_goo" } },
		{ 680, { "#PaintKit_cu_glock_indigo_Tag", "glock_off_world" } },
		{ 681, { "#PaintKit_gs_m4a1_shatter_Tag", "m4a1_leaded_glass" } },
		{ 682, { "#PaintKit_am_mac10_oceani_Tag", "mac10_oceanic" } },
		{ 683, { "#PaintKit_gs_r8_llamacannon_Tag", "r8_llama_cannon" } },
		{ 685, { "#PaintKit_hy_scar20_jungle_slipstream_Tag", "scar20_jungle_slipstream" } },
		{ 684, { "#PaintKit_cu_tec9_cracked_opal_Tag", "tec9_cracked_opal" } },
		{ 686, { "#PaintKit_gs_sg553_phantom_Tag", "sg553_phantom" } },
		{ 687, { "#PaintKit_gs_cz75_tacticat_Tag", "cz75_tacticat" } },
		{ 688, { "#PaintKit_cu_ump45_x-ray_machine_Tag", "ump45_exposure" } },
		{ 689, { "#PaintKit_aq_xm1014_ziggy_anarchy_Tag", "xm1014_ziggy" } },

		/* Clutch Case */
		{ 690, { "#PaintKit_gs_aug_stymphalian_birds_Tag", "aug_stymphalian_birds" } },
		{ 691, { "#PaintKit_gs_awp_death_Tag", "awp_mortis" } },
		{ 692, { "#PaintKit_cu_bizon_riot_Tag", "bizon_night_riot" } },
		{ 693, { "#PaintKit_gs_fiveseven_hot_rod_violet_Tag", "fiveseven_flame_test" } },
		{ 694, { "#PaintKit_aa_glock_18_urban_moon_fever_Tag", "glock_18_moonrise" } },
		{ 695, { "#PaintKit_cu_m4a4_neo_noir_Tag", "m4a4_neo_noir" } },
		{ 696, { "#PaintKit_gs_mp7_bloodsport_Tag", "mp7_bloodsport" } },
		{ 697, { "#PaintKit_cu_mp9_black_sand_Tag", "mp9_black_sand" } },
		{ 698, { "#PaintKit_sp_negev_lionfish_Tag", "negev_lionfish" } },
		{ 699, { "#PaintKit_gs_nova_anchorite_Tag", "nova_wild_six" } },
		{ 700, { "#PaintKit_cu_p2000_urban_hazard_Tag", "p2000_urban_hazard" } },
		{ 701, { "#PaintKit_gs_revolver_tread_Tag", "r8_grip" } },
		{ 702, { "#PaintKit_sp_sg533_aloha_Tag", "sg533_aloha" } },
		{ 703, { "#PaintKit_aq_mag7_swag7_Tag", "mag7_swag7" } },
		{ 704, { "#PaintKit_cu_ump45_white_fang_Tag", "ump45_arctic_wolf" } },
		{ 705, { "#PaintKit_cu_usp_cut_Tag", "usp_cortex" } },
		{ 706, { "#PaintKit_cu_xm1014_oxide_blaze_Tag", "xm1014_oxide_blaze" } },

		/* Horizont Case */
		{ 707, { "#PaintKit_cu_ak_neon_rider_Tag", "ak47_neon_rider" } },
		{ 708, { "#PaintKit_hy_aug_torn_orange_Tag", "aug_slipstream" } },
		{ 709, { "#PaintKit_cu_cz75_eco_Tag", "cz75_eco" } },
		{ 710, { "#PaintKit_sp_elites_winter_raider_Tag", "elites_shred" } },
		{ 711, { "#PaintKit_gs_deagle_aggressor_Tag", "deagle_aggressor" } },
		{ 712, { "#PaintKit_gs_g3sg1_buccaneer_Tag", "g3sg1_high_seas" } },
		{ 713, { "#PaintKit_gs_glock_thunder_dust_Tag", "glock_18_thunder_dust" } },
		{ 714, { "#PaintKit_cu_m4a1s_nightmare_Tag", "m4a1_nightmare" } },
		{ 715, { "#PaintKit_cu_mp9_vein_Tag", "mp9_capillary" } },
		{ 716, { "#PaintKit_cu_nova_toy_soldier_Tag", "nova_toysoldier" } },
		{ 717, { "#PaintKit_gs_p90_tread_Tag", "p90_traction" } },
		{ 718, { "#PaintKit_am_awp_pawpaw_Tag", "awp_pawpaw" } },
		{ 719, { "#PaintKit_gs_powercore_mp7_Tag", "powercore_mp7" } },
		{ 720, { "#PaintKit_cu_sawedoff_devourer_Tag", "sawedoff_devourer" } },
		{ 721, { "#PaintKit_cu_r8_survivalist_Tag", "r8_survivalist" } },
		{ 722, { "#PaintKit_cu_tec9_snake_Tag", "tec9_snake" } },
		{ 723, { "#PaintKit_cu_famas_owl_orange_Tag", "famas_owl_orange" } },

		/* StMark Collections */
		{ 724, { "#PaintKit_cu_ak_island_floral_Tag", "ak47_island_floral" } },
		{ 725, { "#PaintKit_hy_bloom_red_Tag", "bloom_red" } },
		{ 726, { "#PaintKit_sp_bloom_orange_Tag", "bloom_orange" } },
		{ 727, { "#PaintKit_am_bloom_blue_Tag", "bloom_blue" } },
		{ 728, { "#PaintKit_sp_bud_green_Tag", "bud_green" } },
		{ 729, { "#PaintKit_hy_bud_red_Tag", "bud_red" } },
		{ 730, { "#PaintKit_sp_bud_blue_Tag", "bud_blue" } },
		{ 731, { "#PaintKit_hy_leaf_green_Tag", "leaf_green" } },
		{ 732, { "#PaintKit_hy_leaf_blue_Tag", "leaf_blue" } },
		{ 733, { "#PaintKit_sp_leaf_orange_Tag", "leaf_orange" } },
		{ 734, { "#PaintKit_cu_mp9_island_floral_Tag", "mp9_island_floral" } },

		{ 735, { "#PaintKit_sp_nightstripe_Tag", "camo_tape_strips" } },

		/* Canals Collections  */
		{ 736, { "#PaintKit_gs_awp_enamel_Tag", "awp_enamel" } },
		{ 737, { "#PaintKit_gs_mag7_glass_Tag", "mag7_glass" } },
		{ 738, { "#PaintKit_hy_murano_orange_Tag", "murano_orange" } },
		{ 739, { "#PaintKit_am_murano_violet_Tag", "murano_violet" } },
		{ 740, { "#PaintKit_hy_murano_blue_Tag", "murano_blue" } },
		{ 741, { "#PaintKit_am_ren_dark_Tag", "ren_dark" } },
		{ 742, { "#PaintKit_am_ren_red_Tag", "ren_red" } },
		{ 743, { "#PaintKit_hy_ren_orange_Tag", "ren_orange" } },
		{ 744, { "#PaintKit_am_veneto_red_Tag", "veneto_red" } },
		{ 745, { "#PaintKit_hy_veneto_purple_Tag", "veneto_purple" } },
		{ 746, { "#PaintKit_am_veneto2_Tag", "veneto2" } },

		/* Sever Collections*/ 
		{ 756, { "#PaintKit_gs_awp_gungnir_Tag", "awp_gungnir" } },
		{ 757, { "#PaintKit_am_jorm_green_Tag", "jorm_green" } },
		{ 758, { "#PaintKit_am_jorm_orange_Tag", "jorm_orange" } },
		{ 759, { "#PaintKit_am_jorm_blue_Tag", "jorm_blue" } },
		{ 760, { "#PaintKit_am_knots_silver_Tag", "knots_silver" } },
		{ 761, { "#PaintKit_am_knots_brown_Tag", "knots_brown" } },
		{ 762, { "#PaintKit_so_rune_stone_Tag", "rune_stone" } },
		{ 763, { "#PaintKit_gs_negev_thor_Tag", "negev_thor" } },

		/* Dangerzone case */
		{ 801, { "#PaintKit_cu_ak47_asiimov_Tag", "ak47_asiimov" } },
		{ 802, { "#PaintKit_cu_ump_arrows_Tag", "ump45_arrows" } },
		{ 803, { "#PaintKit_cu_awp_neonoir_Tag", "awp_neonoir" } },
		{ 804, { "#PaintKit_gs_mp9_colony01_Tag", "mp9_colony01" } },
		{ 805, { "#PaintKit_gs_deagle_mecha_Tag", "deagle_mecha" } },
		{ 806, { "#PaintKit_gs_g3sg1_savage_Tag", "g3sg1_savage" } },
		{ 807, { "#PaintKit_hy_galil_signal_red_Tag", "galil_signal_red" } },
		{ 808, { "#PaintKit_cu_glock18_corroden_Tag", "glock_18_corroden" } },
		{ 809, { "#PaintKit_gs_nova_hunter_brute_Tag", "nova_hunter_brute" } },
		{ 810, { "#PaintKit_gs_mp5_festival_drip_Tag", "mp5_festival_drip" } },
		{ 811, { "#PaintKit_gs_m4a4_chopper_ghost_Tag", "m4a4_chopper_ghost" } },
		{ 812, { "#PaintKit_gs_mac10_exo_pipes_Tag", "mac10_exo_pipes" } },
		{ 813, { "#PaintKit_aa_p250_gravediggers_Tag", "p250_gravediggers" } },
		{ 814, { "#PaintKit_cu_sawedoff_black_sand_Tag", "sawedoff_black_sand" } },
		{ 815, { "#PaintKit_gs_sg553_over_heated_Tag", "sg553_over_heated" } },
		{ 816, { "#PaintKit_gs_tec9_fubar_Tag", "tec9_fubar" } },
		{ 817, { "#PaintKit_cu_usp_flashback_Tag", "usp_flashback" } },

		/* Prisma Case */
		{ 835, { "#PaintKit_sp_famas_ghost_insects_Tag", "famas_ghost_insects" } },
		{ 836, { "#PaintKit_cu_ak47_aztec_Tag", "ak47_aztec" } },
		{ 837, { "#PaintKit_cu_five_seven_angry_Tag", "five_seven_angry" } },
		{ 838, { "#PaintKit_cu_awp_viper_Tag", "awp_viper" } },
		{ 839, { "#PaintKit_cu_tec9_bamboo_Tag", "tec9_bamboo" } },
		{ 840, { "#PaintKit_gs_mac10_fish_bait_Tag", "mac10_fish_bait" } },
		{ 841, { "#PaintKit_gs_deagle_exo_Tag", "deagle_exo" } },
		{ 842, { "#PaintKit_sp_galil_akoben_Tag", "galil_akoben" } },
		{ 843, { "#PaintKit_cu_revolver_oppressor_Tag", "r8_oppressor" } },
		{ 844, { "#PaintKit_gs_m4a4_emperor_Tag", "m4a4_emperor" } },
		{ 845, { "#PaintKit_cu_aug_momentum_Tag", "aug_momentum" } },
		{ 846, { "#PaintKit_gs_mp5sd_astromatic_Tag", "mp5sd_astromatic" } },
		{ 847, { "#PaintKit_cu_mp7_racketeer_Tag", "mp7_racketeer" } },
		{ 848, { "#PaintKit_aq_p250_verdigris_Tag", "p250_verdigris" } },
		{ 849, { "#PaintKit_cu_p90_offworld_Tag", "p90_offworld" } },
		{ 850, { "#PaintKit_cu_xm1014_incinerator_Tag", "xm1014_incinerator" } },
		{ 851, { "#PaintKit_aa_ump45_moonrise_sunset_Tag", "ump45_moonrise_sunset" } },
		{ 852, { "#PaintKit_am_marbleized_Tag", "doppler_phase1_widow" } },
		{ 853, { "#PaintKit_am_marbleized_Tag", "doppler_phase2_widow" } },
		{ 854, { "#PaintKit_am_marbleized_Tag", "doppler_phase3_widow" } },
		{ 855, { "#PaintKit_am_marbleized_Tag", "doppler_phase4_widow" } },
		{ 856, { "#PaintKit_am_marble_fade_Tag", "marble_fade_widow" } },
		{ 857, { "#PaintKit_aq_damascus_Tag", "damascus_prisma" } },
		{ 858, { "#PaintKit_aq_damascus_Tag", "damascus_widow" } },

		/* Sever Collections*/ 
		{ 859, { "#PaintKit_am_crystallized_green_Tag", "crystallized_green" } }, 
		{ 860, { "#PaintKit_hy_gelpen_dark_Tag", "gelpen_dark" } }, 
		{ 861, { "#PaintKit_sp_asgard_wall_Tag", "asgard_wall" } }, 
		{ 862, { "#PaintKit_am_crystallized_dark_green_Tag", "crystallized_dark_green" } }, 
		{ 863, { "#PaintKit_sp_knots_blue_Tag", "knots_blue" } }, 

		/* Canals Collections*/
		{ 864, { "#PaintKit_so_red_Tag", "red_sg553" } },
		{ 865, { "#PaintKit_hy_canals_tile_Tag", "canals_tile" } },
		{ 866, { "#PaintKit_sp_spray_water_Tag", "spray_water" } },
		{ 867, { "#PaintKit_am_stained_glass_Tag", "stained_glass" } },


		/* StMark Collections*/
		{ 868, { "#PaintKit_hy_flowers_stmarc_Tag", "flowers_stmarc" } },
		{ 869, { "#PaintKit_sp_palm_sunset_Tag", "palm_sunset" } },
		{ 870, { "#PaintKit_sp_palm_green_Tag", "palm_green" } },
		{ 871, { "#PaintKit_sp_twigs_beach_Tag", "twigs_beach" } },
		{ 872, { "#PaintKit_hy_bamboo_stmarc_Tag", "bamboo_stmarc" } },
		{ 873, { "#PaintKit_so_aqua_Tag", "bizon_seabird" } },

		/* Shattered Web */
		{ 884, { "#PaintKit_cu_bizon_road_warrior_Tag", "bizon_road_warrior" } },
		{ 885, { "#PaintKit_gs_ak47_nibbler_Tag", "ak47_nibbler" } },
		{ 886, { "#PaintKit_cu_aug_whitefang_Tag", "aug_whitefang" } },
		{ 887, { "#PaintKit_cu_awp_virus_Tag", "awp_virus" } },
		{ 888, { "#PaintKit_gs_mp5_etch_Tag", "mp5_etch" } },
		{ 889, { "#PaintKit_gs_tec9_decimator_Tag", "tec9_decimator" } },
		{ 890, { "#PaintKit_cu_nova_featherswing_Tag", "nova_featherswing" } },
		{ 891, { "#PaintKit_cu_g3sg1_blacksand_Tag", "g3sg1_blacksand" } },
		{ 892, { "#PaintKit_gs_r8_memento_Tag", "r8_memento" } },
		{ 893, { "#PaintKit_cu_mp7_replica_Tag", "mp7_replica" } },
		{ 894, { "#PaintKit_cu_p2000_obsidian_Tag", "p2000_obsidian" } },
		{ 895, { "#PaintKit_gs_dual_elites_rose_Tag", "dual_elites_rose" } },
		{ 896, { "#PaintKit_sp_scar20_striker_dust_Tag", "scar20_striker_dust" } },
		{ 897, { "#PaintKit_cu_sg553_reactor_Tag", "sg553_reactor" } },
		{ 898, { "#PaintKit_gs_mac10_stalker_Tag", "mac10_stalker" } },
		{ 899, { "#PaintKit_cu_ssg08_tickler_Tag", "ssg08_tickler" } },
		{ 900, { "#PaintKit_gs_m249_warbird_veteran_Tag", "m249_warbird_veteran" } },


		/* CS20 Case */

		{ 902, { "#PaintKit_aq_m249_aztec_Tag", "m249_aztec" } },
		{ 903, { "#PaintKit_gs_dual_elites_classic_Tag", "dual_elites_classic"} },
		{ 904, { "#PaintKit_cu_famas_nuke_tension_Tag", "famas_nuke_tension"} },
		{ 905, { "#PaintKit_cu_tec9_flash_Tag", "tec9_flash" } },
		{ 906, { "#PaintKit_cu_fiveseven_gsg9_Tag", "fiveseven_gsg9" } },
		{ 907, { "#PaintKit_gs_p250_inferno_Tag", "p250_inferno" } },
		{ 908, { "#PaintKit_gs_mac10_dust_crate_Tag", "mac10_dust_crate" } },
		{ 909, { "#PaintKit_gs_mag7_popdog_Tag", "mag7_popdog" } },
		{ 910, { "#PaintKit_cu_mp9_hydra_Tag", "mp9_hydra" } },
		{ 911, { "#PaintKit_cu_p90_nostalgia_Tag", "p90_nostalgia" } },
		{ 913, { "#PaintKit_am_aug_death_by_doggy_Tag", "aug_death_by_doggy" } },
		{ 914, { "#PaintKit_cu_scar_assault_Tag", "scar_assault" } },
		{ 915, { "#PaintKit_gs_mp5_fbi_Tag", "mp5_fbi" } },
		{ 916, { "#PaintKit_cu_ump_bomb_Tag", "ump45_bomb" } },
		{ 917, { "#PaintKit_cu_awp_wildfire_Tag", "awp_wildfire" } },
		{ 918, { "#PaintKit_cu_glock_hero_Tag", "glock_18_hero" } },
		{ 919, { "#PaintKit_gs_famas_legacy_gold_Tag", "famas_legacy_gold" } },

		/* Canals Collections*/
		{ 920, { "#PaintKit_hy_veneto_tan_Tag", "veneto_tan" } },

		/* Prisma 2 Case */
		{941, { "#PaintKit_cu_ak-47_phantom_disruptor_Tag", "ak47_phantom_disruptor"} },
		{942, { "#PaintKit_gs_aug_thunderstorm_Tag", "aug_tom_cat"} },
		{943, { "#PaintKit_cu_awp_vein_Tag", "awp_capillary"} },
		{944, { "#PaintKit_cu_cz75_cerakote_Tag", "cz75_distressed"} },
		{945, { "#PaintKit_cu_deagle_replica_Tag", "deagle_blue_ply"} },
		{946, { "#PaintKit_cu_m4a1s_csgo2048_Tag", "m4a1_two_player"} },
		{947, { "#PaintKit_cu_mac10_nacre_Tag", "mac10_disco_tech"} },
		{948, { "#PaintKit_gs_mag7_justice_Tag", "mag7_justice"} },
		{949, { "#PaintKit_cu_mp5_desert_strike_Tag", "mp5_desert_strike"} },
		{950, { "#PaintKit_cu_negev_prototype_Tag", "negev_prototype"} },
		{951, { "#PaintKit_aq_p2000_acid_clover_Tag", "p2000_acid_etched"} },
		{952, { "#PaintKit_gs_r8_leviathan_Tag", "r8_born_forged"} },
		{953, { "#PaintKit_cu_sawedoff_apocalypto_Tag", "sawedoff_apocalypto"} },
		{954, { "#PaintKit_gs_scar20_enforcer_Tag", "scar20_enforcer"} },
		{955, { "#PaintKit_cu_sg553_darkwing_Tag", "sg553_darkwing"} },
		{956, { "#PaintKit_cu_ssg08_fever_dream_Tag", "ssg08_fever_dream"} },
		{957, { "#PaintKit_cu_glock18_warmaiden_Tag", "glock_18_bullet_queen"} },

		/* Gloves */
		{ 10006, { "#PaintKit_bloodhound_black_silver_tag", "bloodhound_black_silver" } },
		{ 10007, { "#PaintKit_bloodhound_snakeskin_brass_tag", "bloodhound_snakeskin_brass" } },
		{ 10008, { "#PaintKit_bloodhound_metallic_tag", "bloodhound_metallic" } },
		{ 10009, { "#PaintKit_handwrap_leathery_tag", "handwrap_leathery" } },
		{ 10010, { "#PaintKit_handwrap_camo_grey_tag", "handwrap_camo_grey" } },
		{ 10013, { "#PaintKit_slick_black_tag", "slick_black" } },
		{ 10015, { "#PaintKit_slick_military_tag", "slick_military" } },
		{ 10016, { "#PaintKit_slick_red_tag", "slick_red" } },
		{ 10018, { "#PaintKit_sporty_light_blue_tag", "sporty_light_blue" } },
		{ 10019, { "#PaintKit_sporty_military_tag", "sporty_military" } },
		{ 10021, { "#PaintKit_handwrap_red_slaughter_tag", "handwrap_red_slaughter" } },
		{ 10024, { "#PaintKit_motorcycle_basic_black_tag", "motorcycle_basic_black" } },
		{ 10026, { "#PaintKit_motorcycle_mint_triangle_tag", "motorcycle_mint_triangle" } },
		{ 10027, { "#PaintKit_motorcycle_mono_boom_tag", "motorcycle_mono_boom" } },
		{ 10028, { "#PaintKit_motorcycle_triangle_blue_tag", "motorcycle_triangle_blue" } },
		{ 10030, { "#PaintKit_specialist_ddpat_green_camo_tag", "specialist_ddpat_green_camo" } },
		{ 10033, { "#PaintKit_specialist_kimono_diamonds_red_tag", "specialist_kimono_diamonds_red" } },
		{ 10034, { "#PaintKit_specialist_emerald_web_tag", "specialist_emerald_web" } },
		{ 10035, { "#PaintKit_specialist_white_orange_grey_tag", "specialist_orange_white" } },
		{ 10036, { "#PaintKit_handwrap_fabric_orange_camo_tag", "handwrap_fabric_orange_camo" } },
		{ 10037, { "#PaintKit_sporty_purple_tag", "sporty_purple" } },
		{ 10038, { "#PaintKit_sporty_green_tag", "sporty_green" } },
		{ 10039, { "#PaintKit_bloodhound_guerrilla_tag", "bloodhound_guerrilla" } },
		{ 10040, { "#PaintKit_slick_snakeskin_yellow_tag", "slick_snakeskin_yellow" } },
		{ 10041, { "#PaintKit_slick_snakeskin_white_tag", "slick_snakeskin_white" } },
		{ 10042, { "#PaintKit_slick_plaid_purple_tag", "slick_plaid_purple" } },
		{ 10043, { "#PaintKit_slick_stitched_black_orange_tag", "slick_stitched_black_orange" } },
		{ 10044, { "#PaintKit_slick_slick_stitched_green_grey_tag", "slick_stitched_green_grey" } },
		{ 10045, { "#PaintKit_sporty_poison_frog_blue_white_tag", "sporty_poison_frog_blue_white" } },
		{ 10046, { "#PaintKit_sporty_poison_frog_red_green_tag", "sporty_poison_frog_red_green" } },
		{ 10047, { "#PaintKit_sporty_black_webbing_yellow_tag", "sporty_black_webbing_yellow" } },
		{ 10048, { "#PaintKit_sporty_blue_pink_tag", "sporty_blue_pink" } },
		{ 10049, { "#PaintKit_motorcycle_choco_boom_tag", "motorcycle_choco_boom" } },
		{ 10050, { "#PaintKit_motorcycle_basic_green_orange_tag", "motorcycle_basic_green_orange" } },
		{ 10051, { "#PaintKit_motorcycle_yellow_camo_tag", "motorcycle_yellow_camo" } },
		{ 10052, { "#PaintKit_motorcycle_trigrid_blue_tag", "motorcycle_trigrid_blue" } },
		{ 10053, { "#PaintKit_handwrap_leathery_fabric_blue_skulls_tag", "handwrap_leathery_fabric_blue_skulls" } },
		{ 10054, { "#PaintKit_handwrap_leathery_fabric_geometric_blue_tag", "handwrap_leathery_fabric_geometric_blue" } },
		{ 10055, { "#PaintKit_handwrap_leathery_ducttape_tag", "handwrap_leathery_ducttape" } },
		{ 10056, { "#PaintKit_handwrap_leathery_fabric_green_camo_tag", "handwrap_leathery_fabric_green_camo" } },
		{ 10057, { "#PaintKit_bloodhound_hydra_black_green_tag", "bloodhound_hydra_black_green" } },
		{ 10058, { "#PaintKit_bloodhound_hydra_green_leather_mesh_brass_tag", "bloodhound_hydra_green_leather_mesh_brass" } },
		{ 10059, { "#PaintKit_bloodhound_hydra_snakeskin_brass_tag", "bloodhound_hydra_snakeskin_brass" } },
		{ 10060, { "#PaintKit_bloodhound_hydra_case_hardened_tag", "bloodhound_hydra_case_hardened" } },
		{ 10061, { "#PaintKit_specialist_webs_red_tag", "specialist_webs_red" } },
		{ 10062, { "#PaintKit_specialist_forest_brown_tag", "specialist_forest_brown" } },
		{ 10063, { "#PaintKit_specialist_fade_tag", "specialist_fade" } },
		{ 10064, { "#PaintKit_specialist_winterhex_tag", "specialist_winterhex" } },

};

namespace Skins
{
	void Localize();
}
